CREATE OR REPLACE PROCEDURE EXT.SP_CREAR_EXPEDIENTE ()
LANGUAGE SQLSCRIPT 
AS
/*
	----------------------------------------------------------------------------------------------- 
	| Author: Samuel Miralles Manresa 
	| Company: Inycom 
	| Initial Version Date: 05/05/2025 
	|---------------------------------------------------------------------------------------------- 
	| Procedure Purpose: CREACIÓN DE EXPEDIENTES
	| 
	| Version: 1	
	|
	| 
	|
	----------------------------------------------------------------------------------------------- 
*/
BEGIN

	INSERT INTO EXT.CARTERA(RAMO
		, NUM_POLIZA
		, IDPRODUCT
		, IDMODALIDAD
		, NUM_ANUALIDAD
		, FECHA_INICIO
		, FECHA_FIN
		, IDPAIS
		, MODIF_USER
    	, P_INTERMEDIACION
    	, COD_MEDIADOR
    	, COD_SUBCLAVE
    	, NUM_EXPEDIENTE
		, CREATEDATE
		, ACTIVO
    	)
	SELECT RAMO
		, NUM_POLIZA
    	, '' IDPRODUCT
		, IDMODALIDAD
    	, 0 NUM_ANUALIDAD
		, CASE WHEN 1 = (SELECT DISTINCT 1 FROM EXT.CARTERA C
		    				INNER JOIN EXT.RELASUJE R ON 
		    				LPAD(C.NUM_POLIZA,8,0) = R.NUM_POLIZA 
		    				AND LPAD(C.IDMODALIDAD,3,0) = R.MOD
		    				AND C.COD_MEDIADOR || '-' || C.COD_SUBCLAVE = R.POSITIONNAME
		    			  WHERE C.NUM_POLIZA = CT.NUM_POLIZA
	    				)-- EXISTE
	    				THEN (SELECT DISTINCT CASE WHEN MIN(FEC_INI) IS NULL OR MIN(FEC_INI) = '0000-00-00' THEN '1990-12-31'ELSE MIN(FEC_INI) END FROM EXT.CARTERA C
		    				INNER JOIN EXT.RELASUJE R ON 
		    				LPAD(C.NUM_POLIZA,8,0) = R.NUM_POLIZA 
		    				AND LPAD(C.IDMODALIDAD,3,0) = R.MOD
		    				AND C.COD_MEDIADOR || '-' || C.COD_SUBCLAVE = R.POSITIONNAME
		    			  WHERE C.NUM_POLIZA = CT.NUM_POLIZA)
		    			 --NO EXISTE 
	    				ELSE MIN(CT.FECHA_INICIO)
	    	END FECHA_INICIO
	        , CASE WHEN 1 = (SELECT DISTINCT 1 FROM EXT.CARTERA C
		    				INNER JOIN EXT.RELASUJE R ON 
		    				LPAD(C.NUM_POLIZA,8,0) = R.NUM_POLIZA 
		    				AND LPAD(C.IDMODALIDAD,3,0) = R.MOD
		    				AND C.COD_MEDIADOR || '-' || C.COD_SUBCLAVE = R.POSITIONNAME
		    			  WHERE C.NUM_POLIZA = CT.NUM_POLIZA
	    				)-- EXISTE
	    				THEN (SELECT DISTINCT CASE WHEN MAX(FEC_FIN) IS NULL OR MAX(FEC_FIN) = '0000-00-00' THEN '2200-01-01'ELSE MAX(FEC_FIN) END FROM EXT.CARTERA C
		    				INNER JOIN EXT.RELASUJE R ON 
		    				LPAD(C.NUM_POLIZA,8,0) = R.NUM_POLIZA 
		    				AND LPAD(C.IDMODALIDAD,3,0) = R.MOD
		    				AND C.COD_MEDIADOR || '-' || C.COD_SUBCLAVE = R.POSITIONNAME
		    			  WHERE C.NUM_POLIZA = CT.NUM_POLIZA)
		    			 --NO EXISTE 
	    				ELSE MAX(CT.FECHA_FIN)
	    	END FECHA_FIN
		, IDPAIS
        , 'MANUAL-EXPEDIENTE'
        , P_INTERMEDIACION
        , COD_MEDIADOR
        , COD_SUBCLAVE
		, NUM_EXPEDIENTE
		, CURRENT_TIMESTAMP
		, 1 --ACTIVO
	FROM EXT.CARTERA CT
	WHERE CT.RAMO = 'CAUCION' 
	AND 1 = (CASE WHEN EXISTS(SELECT 1 FROM EXT.CARTERA WHERE RAMO = 'CAUCION' AND NUM_POLIZA = CT.NUM_POLIZA AND IDMODALIDAD = CT.IDMODALIDAD 
		AND IDPAIS = CT.IDPAIS AND (IDPRODUCT = '' OR IDPRODUCT IS NULL) AND NUM_FIANZA IS NULL AND NUM_EXPEDIENTE = CT.NUM_EXPEDIENTE) THEN 0 ELSE 1 END)
	GROUP BY CT.RAMO
		, CT.NUM_POLIZA
	 	, CT.IDMODALIDAD
	 	, CT.IDPAIS
	 	, P_INTERMEDIACION
     	, COD_MEDIADOR
     	, COD_SUBCLAVE
		, NUM_EXPEDIENTE;

END;

-- DO BEGIN

-- --	DELETE FROM EXT.CARTERA WHERE MODIF_USER LIKE '%EXPEDIENTE%';
-- 	CALL EXT.SP_CREAR_EXPEDIENTE();
	
-- 	SELECT * FROM EXT.CARTERA WHERE MODIF_USER LIKE '%EXPEDIENTE%'
-- 	AND NUM_POLIZA = 1004250;
-- END;
