CREATE OR REPLACE PROCEDURE EXT.sp_traspaso_mediador_mediador_con_derechos_caucion (IN caseId BIGINT, IN nombreCasoOrigen VARCHAR(100))
LANGUAGE SQLSCRIPT 
AS
/*
	----------------------------------------------------------------------------------------------- 
	| Author: Samuel Miralles Manresa 
	| Company: Inycom 
	| Initial Version Date: 03/02/2025 
	|---------------------------------------------------------------------------------------------- 
	| Procedure Purpose: TRASPASO DE CARTERA DE UN MEDIADOR A OTRO MEDIADOR CON DERECHOS Y OBLIGACIONES CAUCIÓN
	| 
	| Version: 1	
	| Version: 2 SMM 20260209 Cambio traspasos expedientes y avales	
	| Version: 3 SMM 20260318 FECHA_EFECTO y FECHA_VENCIMIENTO NULL en EXPEDIENTES	
	| Version: 4 SMM 20260406	Traspasos con ACTIVO = 1 o ACTIVO =2
	|
	| 
	|
	----------------------------------------------------------------------------------------------- 
*/
BEGIN
    -- DECLARACION DE VARIABLES
    DECLARE i_Tenant VARCHAR(4);
	DECLARE vProcedure VARCHAR(127);
	DECLARE io_contador Number := 0;
    DECLARE v_codMediadorCedente NVARCHAR(100);
    DECLARE v_subClaveMediadorCedente NVARCHAR(100);
    DECLARE v_fechaTraspaso DATE;
    DECLARE v_caseId BIGINT;
    DECLARE v_modifSource NVARCHAR(250);
    DECLARE v_tipoTraspaso NVARCHAR(10);
    DECLARE v_tipoTraspasoCaucion NVARCHAR(100);
	DECLARE v_TipoMovimiento INT;
	DECLARE v_DescTipoMovimiento NVARCHAR(50);
	DECLARE v_ModifUser NVARCHAR(50);

    -- CONSTANTES
    DECLARE cReport CONSTANT VARCHAR(75) := 'sp_traspaso_mediador_mediador_con_derechos_caucion';
    DECLARE cVersion  CONSTANT VARCHAR(3) :='4';
    DECLARE cEsquema CONSTANT VARCHAR(3) := 'EXT';
    DECLARE cRamo CONSTANT VARCHAR(10) := 'CAUCION';
    DECLARE cDerechosObligaciones NVARCHAR(50) := 'CON DERECHOS Y OBLIGACIONES';
    



 ------------------------------- HANDLER EXCEPTION -------------------------
	DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		CALL EXT.LIB_GLOBAL_CESCE:w_debug (i_Tenant, 'SQL ERROR_MESSAGE: ' ||
			IFNULL(::SQL_ERROR_MESSAGE,'') || '. SQL_ERROR_CODE: ' || ::SQL_ERROR_CODE, cReport, io_contador);
	END;
    ---------------------------------------------------------------------------
     --Obtenemos tenant
    SELECT EXT.LIB_GLOBAL_CESCE:getTenantID() INTO i_Tenant FROM DUMMY;

    --Inicio
	CALL EXT.LIB_GLOBAL_CESCE:w_debug (i_Tenant, 'INICIO PROCEDIMIENTO v' || cVersion || ' with SESSION_USER '|| SESSION_USER, CReport, io_contador);
	

	
	
	--OBTENER VALORES
	SELECT DISTINCT 
		CASE WHEN TIPO_TRASPASO = 'N' THEN 'TOTAL' ELSE 'PARCIAL' END
		, COD_MEDIADOR_CEDENTE
		, SUBCLAVE_CEDENTE
		, FECHA_EFECTO_SOLICITUD
		, TIPO_MOVIMIENTO
		, 'MANUAL - CASEID: ' || :caseId
		INTO v_tipoTraspaso,v_codMediadorCedente,v_subClaveMediadorCedente,v_fechaTraspaso,v_TipoMovimiento, v_ModifUser
	FROM EXT.SOLICITUD_TRASPASO WHERE CASEID = :caseId AND RAMO = cRamo AND NUM_POLIZA IS NOT NULL;
   
	-- TIPO MOVIMIENTO
    SELECT CASE 
    	WHEN v_TipoMovimiento = 1 THEN 'SIN MEDIADOR > MEDIADOR'
    	WHEN v_TipoMovimiento = 2 THEN 'MEDIADOR > MEDIADOR'
    	WHEN v_TipoMovimiento = 3 THEN 'TRASPASO %'
    	WHEN v_TipoMovimiento = 4 THEN 'ERROR CAPTURA'
    	WHEN v_TipoMovimiento = 5 THEN 'MEDIADOR > CANAL DIRECTO'
        WHEN v_TipoMovimiento = 6 THEN 'OPERACIONES ESPECIALES'
        WHEN v_TipoMovimiento = 8 THEN 'ENTRE SUBCLAVES'
    	END
    INTO v_DescTipoMovimiento
    FROM DUMMY;

    -- COMPROBAR SI ES TRASPASO TOTAL 'N' O PARCIAL	'P'
    IF ((SELECT COUNT(*) FROM EXT.SOLICITUD_TRASPASO WHERE CASEID = :caseID AND RAMO = cRamo) = (SELECT COUNT(*) FROM EXT.CARTERA WHERE COD_MEDIADOR = :v_codMediadorCedente AND COD_SUBCLAVE = v_subClaveMediadorCedente AND RAMO = cRAMO AND FECHA_VENCIMIENTO >= v_fechaTraspaso AND ACTIVO > 0)) THEN
    	v_tipoTraspaso:= 'TOTAL';
    ELSE
    	v_tipoTraspaso:= 'PARCIAL';
    END IF;
	
	IF EXISTS(SELECT 1 FROM EXT.SOLICITUD_TRASPASO WHERE CASEID = :caseId AND COD_AVAL IS NULL AND RAMO = cRamo AND NUM_POLIZA IS NOT NULL)	THEN	
		v_tipoTraspasoCaucion := 'expediente';
	ELSE
		v_tipoTraspasoCaucion := 'aval';
	END IF;
	
	
	
	IF v_tipoTraspasoCaucion = 'expediente' THEN
		
		CALL EXT.LIB_GLOBAL_CESCE:w_debug (i_Tenant, 'CASE ID: ' ||:caseID|| ' - TRASPASO EXPEDIENTE ' ||v_tipoTraspaso|| ' ' ||:v_DescTipoMovimiento || ' '  || :cDerechosObligaciones  || ' MEDIADOR CEDENTE: '|| :v_codMediadorCedente ||'-'||:v_subClaveMediadorCedente , CReport, io_contador);
	
		v_modifSource:= 'EXPEDIENTE MEDIADOR MEDIADOR '|| :cDerechosObligaciones || ' ' || :caseId;
		
		
		--TRASPASO EXPEDIENTES
		TEMP_EXPEDIENTES = SELECT DISTINCT NUM_POLIZA,COD_MEDIADOR_RECEPTOR,SUBCLAVE_RECEPTOR,INTERMEDIACION_RECEPTOR,FECHA_EFECTO_SOLICITUD,COD_MEDIADOR_CEDENTE,SUBCLAVE_CEDENTE,COD_AVAL
			FROM EXT.SOLICITUD_TRASPASO 
			WHERE CASEID = :caseId AND RAMO = cRamo AND NUM_POLIZA IS NOT NULL AND COD_AVAL IS NULL
			ORDER BY NUM_POLIZA,COD_AVAL;
			
	
		INSERT INTO EXT.CARTERA
			SELECT 
			"RAMO",
			"IDPRODUCT",
			C."NUM_POLIZA",
			"IDMODALIDAD",
			"IDSUBMODALIDAD",
			"NUM_FIANZA",
			"NUM_EXPEDIENTE",
			"NUM_AVAL_HOST",
			"NUM_ANUALIDAD",
			NULL,--"FECHA_EMISION"
			NULL,-- "FECHA_EFECTO"
			NULL,--"FECHA_VENCIMIENTO"
			"IDPAIS",
			"PRIMA_PROVISIONAL_INT",
			"PRIMA_PROVISIONAL_EXT",
			"IDDIVISA_INT",
			"IDDIVISA_EXT",
			"IDDIVISA_COBERTURA",
			"PRIMA_MIN_INT",
			"PRIMA_MIN_EXT",
			T.COD_MEDIADOR_RECEPTOR,
			T.SUBCLAVE_RECEPTOR,
			T.INTERMEDIACION_RECEPTOR,
			(CASE WHEN NUM_FIANZA IS NULL THEN v_fechaTraspaso ELSE FECHA_INICIO END), --FECHA_INICIO
			'2200-01-01', --FECHA_FIN
			"P_ESPECIAL_EMISION",
			"P_ESPECIAL_RENOVACION",
			"NIF_TOMADOR",
			"NOMBRE_TOMADOR",
			v_fechaTraspaso,--C."FECHA_EFECTO_TRASPASO",
			"MEDIADOR_PRINCIPAL_CIC",
			"ACTIVO",
			CURRENT_TIMESTAMP, --CREATION_DATE
			CURRENT_TIMESTAMP, --MODIF_DATE
			v_ModifUser, --CREATION_USER
			nombreCasoOrigen, --MODIF_SOURCE
			NULL, --FECHA_INICIO_OPESP
			NULL -- FECHA_FIN_OPESP
			FROM EXT.CARTERA C INNER JOIN :TEMP_EXPEDIENTES T ON C.NUM_POLIZA = T.NUM_POLIZA AND C.COD_MEDIADOR = T.COD_MEDIADOR_CEDENTE AND C.COD_SUBCLAVE = T.SUBCLAVE_CEDENTE
				AND COALESCE(C.NUM_AVAL_HOST,-1) = COALESCE(T.COD_AVAL,-1)
			WHERE COD_MEDIADOR = :v_codMediadorCedente
			AND COD_SUBCLAVE = :v_subClaveMediadorCedente
			AND RAMO = cRamo
			AND ACTIVO = 1
			-- AND C.NUM_POLIZA = CT.NUM_POLIZA
			
			ORDER BY NUM_POLIZA,NUM_ANUALIDAD;
		
		CALL EXT.LIB_GLOBAL_CESCE:w_debug (i_Tenant, 'EXPEDIENTES INSERTADOS ' || ::ROWCOUNT || ' REGISTROS.', cReport, io_contador);
		
		
		--TRASPASO AVALES
		TEMP_AVAL = SELECT DISTINCT NUM_POLIZA,COD_MEDIADOR_RECEPTOR,SUBCLAVE_RECEPTOR,INTERMEDIACION_RECEPTOR,FECHA_EFECTO_SOLICITUD,COD_MEDIADOR_CEDENTE,SUBCLAVE_CEDENTE,COD_AVAL
			FROM EXT.SOLICITUD_TRASPASO 
			WHERE CASEID = :caseId AND RAMO = cRamo AND NUM_POLIZA IS NOT NULL AND COD_AVAL IS NOT NULL
			ORDER BY NUM_POLIZA,COD_AVAL;
			
	
		INSERT INTO EXT.CARTERA
			SELECT 
			"RAMO",
			"IDPRODUCT",
			C."NUM_POLIZA",
			"IDMODALIDAD",
			"IDSUBMODALIDAD",
			"NUM_FIANZA",
			"NUM_EXPEDIENTE",
			"NUM_AVAL_HOST",
			"NUM_ANUALIDAD",
			"FECHA_EMISION",
			"FECHA_EFECTO",
			"FECHA_VENCIMIENTO",
			"IDPAIS",
			"PRIMA_PROVISIONAL_INT",
			"PRIMA_PROVISIONAL_EXT",
			"IDDIVISA_INT",
			"IDDIVISA_EXT",
			"IDDIVISA_COBERTURA",
			"PRIMA_MIN_INT",
			"PRIMA_MIN_EXT",
			T.COD_MEDIADOR_RECEPTOR,
			T.SUBCLAVE_RECEPTOR,
			T.INTERMEDIACION_RECEPTOR,
			(CASE WHEN NUM_FIANZA IS NULL THEN v_fechaTraspaso ELSE FECHA_INICIO END), --FECHA_INICIO
			'2200-01-01', --FECHA_FIN
			"P_ESPECIAL_EMISION",
			"P_ESPECIAL_RENOVACION",
			"NIF_TOMADOR",
			"NOMBRE_TOMADOR",
			v_fechaTraspaso,--C."FECHA_EFECTO_TRASPASO",
			"MEDIADOR_PRINCIPAL_CIC",
			"ACTIVO",
			CURRENT_TIMESTAMP, --CREATION_DATE
			CURRENT_TIMESTAMP, --MODIF_DATE
			v_ModifUser, --CREATION_USER
			nombreCasoOrigen, --MODIF_SOURCE
			NULL, --FECHA_INICIO_OPESP
			NULL -- FECHA_FIN_OPESP
			FROM EXT.CARTERA C INNER JOIN :TEMP_AVAL T ON C.NUM_POLIZA = T.NUM_POLIZA AND C.COD_MEDIADOR = T.COD_MEDIADOR_CEDENTE AND C.COD_SUBCLAVE = T.SUBCLAVE_CEDENTE
				AND COALESCE(C.NUM_AVAL_HOST,-1) = COALESCE(T.COD_AVAL,-1)
			WHERE COD_MEDIADOR = :v_codMediadorCedente
			AND COD_SUBCLAVE = :v_subClaveMediadorCedente
			AND RAMO = cRamo
			AND ACTIVO > 0
			-- AND C.NUM_POLIZA = CT.NUM_POLIZA
			
			ORDER BY NUM_POLIZA,NUM_ANUALIDAD;
		
		CALL EXT.LIB_GLOBAL_CESCE:w_debug (i_Tenant, 'AVALES INSERTADOS ' || ::ROWCOUNT || ' REGISTROS.', cReport, io_contador);
		
	 
	    --ACTUALIZAMOS MEDIADOR CEDENTE-EXPEDIENTES
	    UPDATE EXT.CARTERA
	    SET ACTIVO = 0,	   
	    FECHA_FIN = (CASE WHEN NUM_FIANZA IS NULL THEN ADD_DAYS(v_fechaTraspaso,-1) ELSE FECHA_FIN END),
	    FECHA_EFECTO_TRASPASO = v_fechaTraspaso,
	    MODIF_USER = v_ModifUser,
	    MODIF_SOURCE = nombreCasoOrigen,
	    MODIF_DATE = CURRENT_TIMESTAMP
	    WHERE COD_MEDIADOR = :v_codMediadorCedente
	    AND COD_SUBCLAVE = :v_subClaveMediadorCedente
	    AND RAMO = cRamo
	    AND ACTIVO > 0
	    AND NUM_POLIZA IN (SELECT NUM_POLIZA FROM EXT.SOLICITUD_TRASPASO WHERE CASEID = :caseId AND RAMO = cRamo AND NUM_POLIZA IS NOT NULL)
	    ;
		
		CALL EXT.LIB_GLOBAL_CESCE:w_debug (i_Tenant, 'ACTUALIZADOS ACTIVO = 0 => ' || ::ROWCOUNT || ' REGISTROS. EXPEDIENTE MEDIADOR CEDENTE ' || :v_codMediadorCedente||'-'||:v_subClaveMediadorCedente, cReport, io_contador);
		
		
		
	ELSE
		CALL EXT.LIB_GLOBAL_CESCE:w_debug (i_Tenant, 'CASE ID: ' ||:caseID|| ' - TRASPASO AVAL ' ||v_tipoTraspaso|| ' ' ||:v_DescTipoMovimiento || ' '  || :cDerechosObligaciones  || ' MEDIADOR CEDENTE: '|| :v_codMediadorCedente ||'-'||:v_subClaveMediadorCedente , CReport, io_contador);
		
		v_modifSource:= 'AVAL MEDIADOR MEDIADOR '|| cDerechosObligaciones ||' ' || :caseId;
		
		TEMP_AVAL = SELECT DISTINCT NUM_POLIZA,COD_MEDIADOR_RECEPTOR,SUBCLAVE_RECEPTOR,INTERMEDIACION_RECEPTOR,FECHA_EFECTO_SOLICITUD,COD_MEDIADOR_CEDENTE,SUBCLAVE_CEDENTE,COD_AVAL
			FROM EXT.SOLICITUD_TRASPASO 
			WHERE CASEID = :caseId AND RAMO = cRamo AND NUM_POLIZA IS NOT NULL AND COD_AVAL IS NOT NULL
			ORDER BY NUM_POLIZA,COD_AVAL;
			

		INSERT INTO EXT.CARTERA
			SELECT 
			"RAMO",
			"IDPRODUCT",
			C."NUM_POLIZA",
			"IDMODALIDAD",
			"IDSUBMODALIDAD",
			"NUM_FIANZA",
			"NUM_EXPEDIENTE",
			"NUM_AVAL_HOST",
			"NUM_ANUALIDAD",
			"FECHA_EMISION",
			"FECHA_EFECTO",
			"FECHA_VENCIMIENTO",
			"IDPAIS",
			"PRIMA_PROVISIONAL_INT",
			"PRIMA_PROVISIONAL_EXT",
			"IDDIVISA_INT",
			"IDDIVISA_EXT",
			"IDDIVISA_COBERTURA",
			"PRIMA_MIN_INT",
			"PRIMA_MIN_EXT",
			T.COD_MEDIADOR_RECEPTOR,
			T.SUBCLAVE_RECEPTOR,
			T.INTERMEDIACION_RECEPTOR,
			(CASE WHEN NUM_FIANZA IS NULL THEN v_fechaTraspaso ELSE FECHA_INICIO END), --FECHA_INICIO
			'2200-01-01', --FECHA_FIN
			"P_ESPECIAL_EMISION",
			"P_ESPECIAL_RENOVACION",
			"NIF_TOMADOR",
			"NOMBRE_TOMADOR",
			v_fechaTraspaso,--C."FECHA_EFECTO_TRASPASO",
			"MEDIADOR_PRINCIPAL_CIC",
			"ACTIVO",
			CURRENT_TIMESTAMP, --CREATION_DATE
			CURRENT_TIMESTAMP, --MODIF_DATE
			v_ModifUser, --CREATION_USER
			nombreCasoOrigen, --MODIF_SOURCE
			NULL, --FECHA_INICIO_OPESP
			NULL -- FECHA_FIN_OPESP
			FROM EXT.CARTERA C INNER JOIN :TEMP_AVAL T ON C.NUM_POLIZA = T.NUM_POLIZA AND C.COD_MEDIADOR = T.COD_MEDIADOR_CEDENTE AND C.COD_SUBCLAVE = T.SUBCLAVE_CEDENTE
				AND COALESCE(C.NUM_AVAL_HOST,-1) = COALESCE(T.COD_AVAL,-1)
			WHERE COD_MEDIADOR = :v_codMediadorCedente
			AND COD_SUBCLAVE = :v_subClaveMediadorCedente
			AND RAMO = cRamo
			AND ACTIVO > 0
			
			ORDER BY NUM_POLIZA,NUM_ANUALIDAD;
		
		CALL EXT.LIB_GLOBAL_CESCE:w_debug (i_Tenant, 'AVALES INSERTADOS ' || ::ROWCOUNT || ' REGISTROS.', cReport, io_contador);
		
	 
		
		--ACTUALIZAMOS MEDIADOR CEDENTE
	    UPDATE EXT.CARTERA
	    SET ACTIVO = 0,	
	    FECHA_EFECTO_TRASPASO = v_fechaTraspaso,
	    MODIF_USER = v_ModifUser,
	    MODIF_SOURCE = nombreCasoOrigen,
	    MODIF_DATE = CURRENT_TIMESTAMP
	    WHERE COD_MEDIADOR = :v_codMediadorCedente
	    AND COD_SUBCLAVE = :v_subClaveMediadorCedente
	    AND RAMO = cRamo
	    AND ACTIVO > 0
	    AND NUM_AVAL_HOST IN (SELECT COD_AVAL FROM EXT.SOLICITUD_TRASPASO WHERE CASEID = :caseId AND RAMO = cRamo AND NUM_POLIZA IS NOT NULL)
	    AND NUM_POLIZA IN (SELECT NUM_POLIZA FROM EXT.SOLICITUD_TRASPASO WHERE CASEID = :caseId AND RAMO = cRamo AND NUM_POLIZA IS NOT NULL)
	    ;
	    CALL EXT.LIB_GLOBAL_CESCE:w_debug (i_Tenant, 'ACTUALIZADOS ACTIVO = 0 => ' || ::ROWCOUNT || ' REGISTROS. MEDIADOR CEDENTE ' || :v_codMediadorCedente||'-'||:v_subClaveMediadorCedente, cReport, io_contador);
	
	END IF;
	
	CALL EXT.LIB_GLOBAL_CESCE:w_debug (i_Tenant, 'FIN PROCEDIMIENTO  with SESSION_USER '|| SESSION_USER, cReport, io_contador);

	
END