CREATE OR REPLACE PROCEDURE EXT.sp_traspaso_porcentaje_mediador_sin_derechos_anualidad_actual_credito (IN caseId BIGINT)
LANGUAGE SQLSCRIPT 
AS
/*
	----------------------------------------------------------------------------------------------- 
	| Author: Samuel Miralles Manresa 
	| Company: Inycom 
	| Initial Version Date: 03/02/2025 
	|---------------------------------------------------------------------------------------------- 
	| Procedure Purpose: TRASPASO % A OTRO MEDIADOR SIN DERECHOS Y OBLIGACIONES EN LA ANUALIDAD ACTUAL
	| 
	| Version: 1	
	|
	| 
	|
	----------------------------------------------------------------------------------------------- 
*/
BEGIN
    -- DECLARACION DE VARIABLES
    DECLARE i_Tenant VARCHAR(4);
	DECLARE vProcedure VARCHAR(127);
	DECLARE io_contador Number := 0;
    DECLARE v_codMediadorCedente NVARCHAR(100);
    DECLARE v_subClaveMediadorCedente NVARCHAR(100);
    DECLARE v_fechaTraspaso DATE;
    DECLARE v_caseId BIGINT;
    DECLARE v_modifSource NVARCHAR(250);
    DECLARE v_tipoTraspaso NVARCHAR(10);
    DECLARE v_tipoTraspasoCaucion NVARCHAR(100);
	DECLARE v_TipoMovimiento INT;
	DECLARE v_DescTipoMovimiento NVARCHAR(50);
    -- CONSTANTES
    DECLARE cReport CONSTANT VARCHAR(250) := 'sp_traspaso_porcentaje_mediador_sin_derechos_anualidad_actual_credito';
    DECLARE cVersion  CONSTANT VARCHAR(3) :='01';
    DECLARE cEsquema CONSTANT VARCHAR(3) := 'EXT';
    DECLARE cRamo CONSTANT VARCHAR(10) := 'CREDITO';
    DECLARE cDerechosObligaciones NVARCHAR(50) := 'SIN DERECHOS Y OBLIGACIONES ANUALIDAD ACTUAL ';
    
    -- DECLARACION DE CURSOR    
    DECLARE CURSOR CURSOR_TRASPASOS FOR
	SELECT DISTINCT NUM_POLIZA,COD_MEDIADOR_RECEPTOR,SUBCLAVE_RECEPTOR,INTERMEDIACION_RECEPTOR,FECHA_EFECTO_SOLICITUD,COD_MEDIADOR_CEDENTE,SUBCLAVE_CEDENTE
	FROM EXT.SOLICITUD_TRASPASO 
	WHERE CASEID = :caseId;
    

    ------------------------------- HANDLER EXCEPTION -------------------------
	DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		CALL EXT.LIB_GLOBAL_CESCE:w_debug (i_Tenant, 'SQL ERROR_MESSAGE: ' ||
			IFNULL(::SQL_ERROR_MESSAGE,'') || '. SQL_ERROR_CODE: ' || ::SQL_ERROR_CODE, cReport, io_contador);
	END;
    ---------------------------------------------------------------------------
     --Obtenemos tenant
    SELECT EXT.LIB_GLOBAL_CESCE:getTenantID() INTO i_Tenant FROM DUMMY;

    --Inicio
	CALL EXT.LIB_GLOBAL_CESCE:w_debug (i_Tenant, 'INICIO PROCEDIMIENTO v' || cVersion || ' with SESSION_USER '|| SESSION_USER, CReport, io_contador);


    SELECT * FROM EXT.SOLICITUD_TRASPASO WHERE CASEID = :caseId;
	
	--OBTENER VALORES
	SELECT DISTINCT 
		CASE WHEN TIPO_TRASPASO = 'N' THEN 'TOTAL' ELSE 'PARCIAL' END
		, COALESCE(COD_MEDIADOR_CEDENTE,'0000')
		, COALESCE(SUBCLAVE_CEDENTE,'0000')
		, FECHA_EFECTO_SOLICITUD
		, TIPO_MOVIMIENTO
		INTO v_tipoTraspaso,v_codMediadorCedente,v_subClaveMediadorCedente,v_fechaTraspaso,v_TipoMovimiento 
	FROM EXT.SOLICITUD_TRASPASO WHERE CASEID = :caseId;
	
    -- TIPO MOVIMIENTO
    SELECT CASE 
    	WHEN v_TipoMovimiento = 1 THEN 'SIN MEDIADOR > MEDIADOR'
    	WHEN v_TipoMovimiento = 2 THEN 'MEDIADOR > MEDIADOR'
    	WHEN v_TipoMovimiento = 3 THEN 'TRASPASO %'
    	WHEN v_TipoMovimiento = 5 THEN 'MEDIADOR > CANAL DIRECTO'
    	END
    INTO v_DescTipoMovimiento
    FROM DUMMY;
    
    -- COMPROBAR SI ES TRASPASO TOTAL 'N' O PARCIAL	'P'
    -- IF ((SELECT COUNT(*) FROM EXT.SOLICITUD_TRASPASO WHERE CASEID = :caseID) = (SELECT COUNT(*) FROM EXT.CARTERA WHERE COD_MEDIADOR = :v_codMediadorCedente AND COD_SUBCLAVE = v_subClaveMediadorCedente AND RAMO = cRAMO AND FECHA_VENCIMIENTO >= v_fechaTraspaso)) THEN
    -- 	v_tipoTraspaso:= 'TOTAL';
    -- ELSE
    	v_tipoTraspaso:= 'PARCIAL';
    -- END IF;
    
   
	--  IF v_tipoTraspaso = 'TOTAL' THEN
	-- 	v_modifSource:= 'TRASPASO TOTAL '||:v_DescTipoMovimiento|| ' ' || cDerechosObligaciones || ' - CASEID: ' || :caseId;
	-- ELSE
		v_modifSource:= 'TRASPASO PARCIAL '||:v_DescTipoMovimiento|| ' ' || cDerechosObligaciones || ' - CASEID: ' || :caseId;
	-- END IF;

    CALL EXT.LIB_GLOBAL_CESCE:w_debug (i_Tenant, 'TRASPASO ' ||:v_tipoTraspaso|| ' ' ||:v_DescTipoMovimiento || ' '  || :cDerechosObligaciones  || ' MEDIADOR CEDENTE: '|| :v_codMediadorCedente ||'-'||:v_subClaveMediadorCedente , CReport, io_contador);
	
	
	
	-- ABRIR CURSOR
     OPEN CURSOR_TRASPASOS;

    FOR CT AS CURSOR_TRASPASOS DO
 
    INSERT INTO EXT.CARTERA 
    WITH CTE AS (
    SELECT *
    	--, ADD_DAYS(FECHA_VENCIMIENTO,1) NEW_FECHA_VENCIMIENTO
        ,ROW_NUMBER() OVER (PARTITION BY NUM_POLIZA, COD_MEDIADOR ORDER BY NUM_ANUALIDAD DESC) AS RN
    FROM EXT.CARTERA 
    WHERE COD_MEDIADOR = :v_codMediadorCedente
    AND RAMO = 'CREDITO'
	AND ACTIVO = 1
	AND NUM_POLIZA = CT.NUM_POLIZA
	)
	SELECT "RAMO",
		"IDPRODUCT",
		"NUM_POLIZA",
		"IDMODALIDAD",
		"IDSUBMODALIDAD",
		"NUM_FIANZA",
		"NUM_EXPEDIENTE",
		"NUM_AVAL_HOST",
		"NUM_ANUALIDAD",
		"FECHA_EMISION",
		"FECHA_EFECTO",
		"FECHA_VENCIMIENTO",
		"IDPAIS",
		"PRIMA_PROVISIONAL_INT",
		"PRIMA_PROVISIONAL_EXT",
		"IDDIVISA_INT",
		"IDDIVISA_EXT",
		"IDDIVISA_COBERTURA",
		"PRIMA_MIN_INT",
		"PRIMA_MIN_EXT",
		CT.COD_MEDIADOR_RECEPTOR,
        CT.SUBCLAVE_RECEPTOR,
        CT.INTERMEDIACION_RECEPTOR,
		CT.FECHA_EFECTO_SOLICITUD,
		'2200-01-01',
		"P_ESPECIAL_EMISION",
		"P_ESPECIAL_RENOVACION",
		"NIF_TOMADOR",
		"NOMBRE_TOMADOR",
		"FECHA_EFECTO_TRASPASO",
		"MEDIADOR_PRINCIPAL_CIC",
		1,
		CURRENT_TIMESTAMP,
		CURRENT_TIMESTAMP,
		'SMM',
		v_modifSource,
		NULL,
		NULL 
	FROM CTE
	WHERE RN = 1
	ORDER BY NUM_POLIZA, NUM_ANUALIDAD;
	
	CALL EXT.LIB_GLOBAL_CESCE:w_debug (i_Tenant, 'INSERTADOS ' || ::ROWCOUNT || ' REGISTROS. PÓLIZA ' || CT.NUM_POLIZA || ' - MEDIADOR RECEPTOR ' || CT.COD_MEDIADOR_RECEPTOR||'-'||CT.SUBCLAVE_RECEPTOR, cReport, io_contador);
	
  END FOR; 
  CLOSE CURSOR_TRASPASOS;
    --ACTUALIZAMOS MEDIADOR CEDENTE
 
	UPDATE C
	SET P_INTERMEDIACION = C.P_INTERMEDIACION - (SELECT SUM(INTERMEDIACION_RECEPTOR) FROM (SELECT COD_MEDIADOR_RECEPTOR,INTERMEDIACION_RECEPTOR FROM EXT.SOLICITUD_TRASPASO WHERE CASEID = :caseId GROUP BY COD_MEDIADOR_RECEPTOR,INTERMEDIACION_RECEPTOR))		
		, MODIF_USER = 'SMM'
		, MODIF_SOURCE = v_modifSource
		, MODIF_DATE = CURRENT_TIMESTAMP
	FROM EXT.CARTERA C INNER JOIN (SELECT *
						FROM (
							SELECT *
							,ROW_NUMBER() OVER (PARTITION BY NUM_POLIZA, COD_MEDIADOR ORDER BY NUM_ANUALIDAD DESC) AS RN
							FROM EXT.CARTERA CRT WHERE COD_MEDIADOR = CRT.COD_MEDIADOR AND NUM_POLIZA = CRT.NUM_POLIZA AND RAMO = 'CREDITO' AND ACTIVO = 1
							
						) WHERE RN = 1) CT ON C.NUM_POLIZA = CT.NUM_POLIZA AND C.COD_MEDIADOR = CT.COD_MEDIADOR AND C.COD_SUBCLAVE = CT.COD_SUBCLAVE AND C.NUM_ANUALIDAD = CT.NUM_ANUALIDAD
	WHERE C.COD_MEDIADOR = v_codMediadorCedente
	AND C.COD_SUBCLAVE = v_subClaveMediadorCedente
	AND C.RAMO = 'CREDITO'
	AND C.ACTIVO = 1
	AND C.NUM_POLIZA IN (SELECT DISTINCT NUM_POLIZA FROM EXT.SOLICITUD_TRASPASO WHERE CASEID = :caseId)
	;
    
    CALL EXT.LIB_GLOBAL_CESCE:w_debug (i_Tenant, 'ACTUALIZADOS ' || ::ROWCOUNT || ' REGISTROS. MEDIADOR CEDENTE ' || :v_codMediadorCedente||'-'||:v_subClaveMediadorCedente, cReport, io_contador);
	
    CALL EXT.LIB_GLOBAL_CESCE:w_debug (i_Tenant, 'FIN PROCEDIMIENTO ' || cVersion || ' with SESSION_USER '|| SESSION_USER, cReport, io_contador);



END;


DO BEGIN 
DECLARE vRAMO VARCHAR(50) = 'CREDITO';
DECLARE vCASEID BIGINT = 1793;


TRUNCATE TABLE EXT.CARTERA;
INSERT INTO EXT.CARTERA SELECT * FROM EXT.CARTERA_BKP_04022025 ;
DELETE FROM EXT.CSE_DEBUG WHERE PROCESO LIKE '%sp_traspaso_porcentaje_mediador_sin_derechos_anualidad_actual_credito%';

CALL EXT.sp_traspaso_porcentaje_mediador_sin_derechos_anualidad_actual_credito(vCASEID);

SELECT ACTIVO,IDPAIS,IDPRODUCT,NUM_POLIZA,NUM_ANUALIDAD,NUM_AVAL_HOST,COD_MEDIADOR,COD_SUBCLAVE,P_INTERMEDIACION,FECHA_INICIO,FECHA_FIN,MODIF_SOURCE,MODIF_DATE,MODIF_USER 
FROM EXT.CARTERA 
WHERE (COD_MEDIADOR IN('0004') OR MODIF_USER = 'SMM') AND RAMO = vRAMO ORDER BY COD_MEDIADOR,NUM_AVAL_HOST,NUM_POLIZA,NUM_ANUALIDAD;


SELECT * FROM EXT.CSE_DEBUG WHERE PROCESO LIKE '%sp_traspaso_porcentaje_mediador_sin_derechos_anualidad_actual_credito%';


--UPDATE EXT.SOLICITUD_TRASPASO SET COD_MEDIADOR_CEDENTE = '0004', SUBCLAVE_CEDENTE = '0000' WHERE CASEID = vCASEID;

SELECT SUM(INTERMEDIACION_RECEPTOR) FROM (SELECT COD_MEDIADOR_RECEPTOR,INTERMEDIACION_RECEPTOR FROM EXT.SOLICITUD_TRASPASO WHERE CASEID = 1793 GROUP BY COD_MEDIADOR_RECEPTOR,INTERMEDIACION_RECEPTOR);
END;