CREATE OR REPLACE PROCEDURE EXT.sp_traspaso_mediador_mediador_con_derechos_credito_caseid (IN caseId BIGINT)
LANGUAGE SQLSCRIPT 
AS
/*
	----------------------------------------------------------------------------------------------- 
	| Author: Samuel Miralles Manresa 
	| Company: Inycom 
	| Initial Version Date: 03/02/2025 
	|---------------------------------------------------------------------------------------------- 
	| Procedure Purpose: TRASPASO DE CARTERA DE UN MEDIADOR A OTRO MEDIADOR CON DERECHOS Y OBLIGACIONES
	| 
	| Version: 1	
	|
	| 
	|
	----------------------------------------------------------------------------------------------- 
*/
BEGIN
    -- DECLARACION DE VARIABLES
    DECLARE i_Tenant VARCHAR(4);
	DECLARE vProcedure VARCHAR(127);
	DECLARE io_contador Number := 0;
    DECLARE v_codMediadorCedente NVARCHAR(100);
    DECLARE v_subClaveMediadorCedente NVARCHAR(100);
    DECLARE v_fechaTraspaso DATE;
    DECLARE v_caseId BIGINT;
    DECLARE v_modifSource NVARCHAR(250);
    DECLARE v_tipoTraspaso NVARCHAR(10);
    DECLARE v_tipoTraspasoCaucion NVARCHAR(100);
	DECLARE cTipoMovimiento NVARCHAR(50);
    -- CONSTANTES
    DECLARE cReport CONSTANT VARCHAR(50) := 'sp_traspaso_mediador_mediador_con_derechos_credito';
    DECLARE cVersion  CONSTANT VARCHAR(3) :='01';
    DECLARE cEsquema CONSTANT VARCHAR(3) := 'EXT';
    DECLARE cRamo CONSTANT VARCHAR(10) := 'CREDITO';
    DECLARE cDerechosObligaciones NVARCHAR(50) := 'CON DERECHOS Y OBLIGACIONES';
    
    DECLARE CURSOR CURSOR_TRASPASOS FOR
	SELECT DISTINCT NUM_POLIZA,COD_MEDIADOR_RECEPTOR,SUBCLAVE_RECEPTOR,INTERMEDIACION_RECEPTOR,FECHA_EFECTO_SOLICITUD,COD_MEDIADOR_CEDENTE,SUBCLAVE_CEDENTE
	FROM EXT.SOLICITUD_TRASPASO 
	WHERE CASEID = :caseId;
	
 ------------------------------- HANDLER EXCEPTION -------------------------
	DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		CALL EXT.LIB_GLOBAL_CESCE:w_debug (i_Tenant, 'SQL ERROR_MESSAGE: ' ||
			IFNULL(::SQL_ERROR_MESSAGE,'') || '. SQL_ERROR_CODE: ' || ::SQL_ERROR_CODE, cReport, io_contador);
	END;
    ---------------------------------------------------------------------------
     --Obtenemos tenant
    SELECT EXT.LIB_GLOBAL_CESCE:getTenantID() INTO i_Tenant FROM DUMMY;

    --Inicio
	CALL EXT.LIB_GLOBAL_CESCE:w_debug (i_Tenant, 'INICIO PROCEDIMIENTO v' || cVersion || ' with SESSION_USER '|| SESSION_USER, CReport, io_contador);


	SELECT * FROM EXT.SOLICITUD_TRASPASO WHERE CASEID = :caseId;
	
	--OBTENER VALORES
	SELECT DISTINCT 
		CASE WHEN TIPO_TRASPASO = 'N' THEN 'TOTAL' ELSE 'PARCIAL' END
		, COD_MEDIADOR_CEDENTE
		, SUBCLAVE_CEDENTE
		, FECHA_EFECTO_SOLICITUD
		INTO v_tipoTraspaso,v_codMediadorCedente,v_subClaveMediadorCedente,v_fechaTraspaso 
	FROM EXT.SOLICITUD_TRASPASO WHERE CASEID = :caseId;
	
    
    -- COMPROBAR SI ES TRASPASO TOTAL 'N' O PARCIAL	'P'
	IF v_tipoTraspaso = 'TOTAL' THEN
		v_modifSource:= 'TRASPASO TOTAL MEDIADOR MEDIADOR CON DERECHOS Y OBLIGACIONES ' || :caseId;
	ELSE
		v_modifSource:= 'TRASPASO PARCIAL MEDIADOR MEDIADOR CON DERECHOS Y OBLIGACIONES ' || :caseId;
	END IF;
	
	
	
	CALL EXT.LIB_GLOBAL_CESCE:w_debug (i_Tenant, 'TRASPASO MEDIADOR > MEDIADOR ' || UPPER(:v_tipoTraspaso)  || ' MEDIADOR CEDENTE: '|| :v_codMediadorCedente ||'-'||:v_subClaveMediadorCedente , CReport, io_contador);
	
    OPEN CURSOR_TRASPASOS;
    FOR CT AS CURSOR_TRASPASOS DO
		-- SELECT 	CT.NUM_POLIZA,CT.COD_MEDIADOR_RECEPTOR,CT.SUBCLAVE_RECEPTOR,CT.INTERMEDIACION_RECEPTOR,CT.FECHA_EFECTO_SOLICITUD FROM DUMMY;
		-- INSERTAMOS PÓLIZAS MEDIADOR RECEPTOR
        INSERT INTO EXT.CARTERA 
        SELECT 
        C."RAMO",
        C."IDPRODUCT",
        C."NUM_POLIZA",
        C."IDMODALIDAD",
        C."IDSUBMODALIDAD",
        C."NUM_FIANZA",
        C."NUM_EXPEDIENTE",
        C."NUM_AVAL_HOST",
        C."NUM_ANUALIDAD",
        C."FECHA_EMISION",
        C."FECHA_EFECTO",
        C."FECHA_VENCIMIENTO",
        C."IDPAIS",
        C."PRIMA_PROVISIONAL_INT",
        C."PRIMA_PROVISIONAL_EXT",
        C."IDDIVISA_INT",
        C."IDDIVISA_EXT",
        C."IDDIVISA_COBERTURA",
        C."PRIMA_MIN_INT",
        C."PRIMA_MIN_EXT",
        CT.COD_MEDIADOR_RECEPTOR,
        CT.SUBCLAVE_RECEPTOR,
        CT.INTERMEDIACION_RECEPTOR,
        CT.FECHA_EFECTO_SOLICITUD,
        '2200-01-01',
        CASE WHEN
        	CRT.NUM_ANUALIDAD IS NOT NULL THEN C.P_ESPECIAL_EMISION
        END, --P_ESPECIAL_EMISION
        CASE 
        	--ANUALIDAD VIGENTE TIENE P_ESPECIAL_RENOVACION
        	WHEN CRT.NUM_ANUALIDAD IS NOT NULL AND C.P_ESPECIAL_RENOVACION IS NOT NULL THEN C.P_ESPECIAL_RENOVACION
        	--ANUALIDAD VIGENTE TIENE P_ESPECIAL_EMISION Y NO TIENE P_ESPECIAL_RENOVACION
        	WHEN CRT.NUM_ANUALIDAD IS NOT NULL AND C.P_ESPECIAL_EMISION IS NOT NULL AND (C.P_ESPECIAL_RENOVACION IS NULL OR C.P_ESPECIAL_RENOVACION = 0) THEN PP.P_RENOV_FIN 
        END, --P_ESPECIAL_RENOVACION
        C."NIF_TOMADOR",
        C."NOMBRE_TOMADOR",
        C."FECHA_EFECTO_TRASPASO",
        C."MEDIADOR_PRINCIPAL_CIC",
        C."ACTIVO",
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP,
        'SMM',
        v_modifSource,
        CASE WHEN
        	CRT.NUM_ANUALIDAD IS NOT NULL AND ((C.P_ESPECIAL_EMISION IS NULL AND C.P_ESPECIAL_EMISION = 0)  OR (C.P_ESPECIAL_RENOVACION IS NULL AND C.P_ESPECIAL_RENOVACION = 0)) THEN
        		CT.FECHA_EFECTO_SOLICITUD
        END, -- FECHA_INICIO_OPESP
        CASE WHEN
        	CRT.NUM_ANUALIDAD IS NOT NULL AND ((C.P_ESPECIAL_EMISION IS NOT NULL AND C.P_ESPECIAL_EMISION <> 0)  OR (C.P_ESPECIAL_RENOVACION IS NOT NULL AND C.P_ESPECIAL_RENOVACION <> 0)) THEN
        		C.FECHA_VENCIMIENTO
        END -- FECHA_FIN_OPESP
        FROM EXT.CARTERA C LEFT JOIN (SELECT *
						FROM (
							SELECT *
							,ROW_NUMBER() OVER (PARTITION BY CR.NUM_POLIZA, CR.COD_MEDIADOR ORDER BY CR.NUM_ANUALIDAD DESC) AS RN
							FROM EXT.CARTERA CR WHERE CR.COD_MEDIADOR = CT.COD_MEDIADOR_CEDENTE AND CR.NUM_POLIZA = CT.NUM_POLIZA AND CR.RAMO = 'CREDITO' AND CR.ACTIVO = 1
							AND CR.NUM_POLIZA = CT.NUM_POLIZA
							
						) WHERE RN = 1) CRT ON C.NUM_POLIZA = CRT.NUM_POLIZA AND C.COD_MEDIADOR = CRT.COD_MEDIADOR AND C.COD_SUBCLAVE = CRT.COD_SUBCLAVE AND C.NUM_ANUALIDAD = CRT.NUM_ANUALIDAD
		LEFT JOIN (
	        SELECT 
	            CART.NUM_POLIZA,
	            CART.COD_MEDIADOR,
	            CART.COD_SUBCLAVE,
	            CART.IDMODALIDAD,
	            ROW_NUMBER() OVER (
	                PARTITION BY CART.NUM_POLIZA, CART.COD_MEDIADOR, CART.COD_SUBCLAVE, CART.IDMODALIDAD
	                ORDER BY CART.NUM_ANUALIDAD DESC, CART.ACTIVO DESC
	            ) AS RN,
	            CASE 
	                WHEN CART.P_ESPECIAL_EMISION IS NULL OR CART.P_ESPECIAL_EMISION = 0 
	                THEN COALESCE(PC.P_EMISION, PV.P_EMISION_DEF)
	                ELSE CART.P_ESPECIAL_EMISION 
	            END AS P_EMISION_FIN,
	            CASE 
	                WHEN CART.P_ESPECIAL_RENOVACION IS NULL OR CART.P_ESPECIAL_RENOVACION = 0 
	                THEN COALESCE(PC.P_RENOVACION, PV.P_RENOVACION_DEF)
	                ELSE CART.P_ESPECIAL_RENOVACION 
	            END AS P_RENOV_FIN
	        FROM EXT.CARTERA CART
	        LEFT JOIN EXT.PLAN_COMISIONAMIENTO PC 
	            ON CART.COD_MEDIADOR || '-' || CART.COD_SUBCLAVE = PC.POSITIONNAME 
	            AND CART.IDPRODUCT = PC.IDPRODUCT 
	            AND CART.FECHA_EFECTO >= PC.EFFECTIVESTARTDATE 
	            AND CART.FECHA_EFECTO < PC.EFFECTIVEENDDATE
	        LEFT JOIN EXT.PRODUCTOS_VW PV 
	            ON CART.IDPRODUCT = PV.IDPRODUCT AND CART.IDMODALIDAD = PV.MODALIDAD
	    ) PP ON PP.NUM_POLIZA = C.NUM_POLIZA AND PP.COD_MEDIADOR = C.COD_MEDIADOR
				AND PP.COD_SUBCLAVE = C.COD_SUBCLAVE AND PP.RN = 1
        WHERE C.COD_MEDIADOR = CT.COD_MEDIADOR_CEDENTE
        AND C.COD_SUBCLAVE = CT.SUBCLAVE_CEDENTE
        AND C.RAMO = 'CREDITO'
        AND C.ACTIVO = 1
        AND C.NUM_POLIZA = CT.NUM_POLIZA
        ORDER BY C.NUM_POLIZA,C.NUM_ANUALIDAD;
        
        CALL EXT.LIB_GLOBAL_CESCE:w_debug (i_Tenant, 'INSERTADOS ' || ::ROWCOUNT || ' REGISTROS. PÓLIZA ' || CT.NUM_POLIZA || ' - MEDIADOR RECEPTOR ' || CT.COD_MEDIADOR_RECEPTOR||'-'||CT.SUBCLAVE_RECEPTOR, cReport, io_contador);
	
    END FOR;
    CLOSE CURSOR_TRASPASOS;
    
    
    -- --ACTUALIZAMOS MEDIADOR CEDENTE
    UPDATE EXT.CARTERA
    SET ACTIVO = 0,
    FECHA_FIN = ADD_DAYS(v_fechaTraspaso,-1),
    MODIF_USER = 'SMM',
    MODIF_SOURCE = v_modifSource,
    MODIF_DATE = CURRENT_TIMESTAMP
    WHERE COD_MEDIADOR = :v_codMediadorCedente
    AND COD_SUBCLAVE = :v_subClaveMediadorCedente
    AND RAMO = 'CREDITO'
    AND ACTIVO = 1
    AND NUM_POLIZA IN (SELECT DISTINCT NUM_POLIZA FROM EXT.SOLICITUD_TRASPASO WHERE CASEID = :caseId)
    ;
	
	CALL EXT.LIB_GLOBAL_CESCE:w_debug (i_Tenant, 'ACTUALIZADOS ' || ::ROWCOUNT || ' REGISTROS. MEDIADOR CEDENTE ' || :v_codMediadorCedente||'-'||:v_subClaveMediadorCedente, cReport, io_contador);
	
    CALL EXT.LIB_GLOBAL_CESCE:w_debug (i_Tenant, 'FIN PROCEDIMIENTO ' || cVersion || ' with SESSION_USER '|| SESSION_USER, cReport, io_contador);

END;


DO BEGIN 


TRUNCATE TABLE EXT.CARTERA;
INSERT INTO EXT.CARTERA SELECT * FROM EXT.CARTERA_BKP_04022025;

DELETE FROM EXT.CSE_DEBUG WHERE PROCESO LIKE '%sp_traspaso_mediador_mediador_con_derechos_credito%';

UPDATE EXT.CARTERA SET P_ESPECIAL_EMISION = 0.10 WHERE NUM_POLIZA = 22751 AND RAMO = 'CREDITO' AND NUM_ANUALIDAD IN (2,3);

SELECT ACTIVO,NUM_POLIZA,NUM_ANUALIDAD,COD_MEDIADOR,FECHA_EMISION,FECHA_EFECTO,FECHA_VENCIMIENTO,P_INTERMEDIACION,FECHA_INICIO,FECHA_FIN,P_ESPECIAL_EMISION,P_ESPECIAL_RENOVACION,FECHA_INICIO_OPESP,FECHA_FIN_OPESP FROM EXT.CARTERA WHERE COD_MEDIADOR = '0004' AND RAMO = 'CREDITO' ORDER BY COD_MEDIADOR,NUM_POLIZA,NUM_ANUALIDAD;

CALL EXT.sp_traspaso_mediador_mediador_con_derechos_credito_caseid(1781);

SELECT ACTIVO,NUM_POLIZA,NUM_ANUALIDAD,COD_MEDIADOR,FECHA_EMISION,FECHA_EFECTO,FECHA_VENCIMIENTO,P_INTERMEDIACION,FECHA_INICIO,FECHA_FIN,P_ESPECIAL_EMISION,P_ESPECIAL_RENOVACION,FECHA_INICIO_OPESP,FECHA_FIN_OPESP FROM EXT.CARTERA WHERE (COD_MEDIADOR = '0004' OR MODIF_USER = 'SMM') AND RAMO = 'CREDITO' ORDER BY COD_MEDIADOR,NUM_POLIZA,NUM_ANUALIDAD;

SELECT * FROM EXT.CSE_DEBUG WHERE PROCESO LIKE '%sp_traspaso_mediador_mediador_con_derechos_credito%';





END;