CREATE VIEW "EXT"."CSA_INF_DETALLE_LIQUIDACION_RM_SVW" ( "CODIGO", "MEDIADOR", "IDRECIBO", "IDPAIS", "PAIS", "COMPANIA", "SUCURSAL", "CONCEPTO", "DESCRIPCION_PRODUCTO", "MODALIDAD", "NUM_POLIZA", "TOMADOR", "NUM_FACTURA", "FECHA_EFECTO_ANUALIDAD", "FECHA_COBRO", "MESCIERRE", "MONEDA", "IDTIPOCOMISION", "TIPOCOMISION", "IDTIPO_MVTO", "TIPO_MVTO", "IMPORTE_COBRADA", "IMPORTE_COM_COBRADA", "PERIODSEQ", "POSITIONSEQ" ) 
AS (SELECT CODIGO
	, MEDIADOR
	, IDRECIBO
	, IDPAIS
	, PAIS
	, COMPANIA
	, SUCURSAL
	, CONCEPTO
	, DESCRIPCION_PRODUCTO
	, MODALIDAD
	, NUM_POLIZA
	, TOMADOR
	, NUM_FACTURA
	, FECHA_EFECTO_ANUALIDAD
	, FECHA_COBRO
	, MESCIERRE
	, MONEDA
	, IDTIPOCOMISION
	, TIPOCOMISION
	, IDTIPO_MVTO
	, TIPO_MVTO
	, IMPORTE_COBRADA
	, IMPORTE_COM_COBRADA
	, PERIODSEQ
	, POSITIONSEQ
	FROM EXT.INF_DETALLE_LIQUIDACION_RM)
WITH READ ONLY STRUCTURED PRIVILEGE CHECK;