DO BEGIN

    DECLARE VBATCHNAME VARCHAR(255) = '1689_MVFID_PRD_20240912_061502_MovFianzas.txt';

    /***********************************************************************/
    -- Obtener cantidad de diferencias entre las tablas
    -- EXT.EXT_MOVIMIENTO_FIANZAS_CAUCION_HIST
    -- EXT.EXT_MOVIMIENTO_CARTERA_CREDITO_HIST
    -- EXT.CARTERA
    /***********************************************************************/
    SELECT 
        COALESCE(CARTERA.MODIF_SOURCE, MVFID.BATCHNAME,MVCAR.BATCHNAME) AS nombre_fichero,
        COALESCE(MVFID.CANT_MVFID, 0) AS CANT_MVFID,
        COALESCE(MVCAR.CANT_MVCAR, 0) AS CANT_MVCAR,
        COALESCE(CARTERA.CANT_CARTERA, 0) AS CANT_CARTERA
    FROM 
        (SELECT C.MODIF_SOURCE, COUNT(*) AS CANT_CARTERA FROM EXT.CARTERA C GROUP BY C.MODIF_SOURCE) CARTERA
    FULL OUTER JOIN 
        (SELECT MVFID.BATCHNAME, COUNT(*) AS CANT_MVFID FROM EXT.EXT_MOVIMIENTO_FIANZAS_CAUCION_HIST MVFID GROUP BY MVFID.BATCHNAME) MVFID
    ON CARTERA.MODIF_SOURCE = MVFID.BATCHNAME
    FULL OUTER JOIN 
    (SELECT MVCAR.BATCHNAME, COUNT(*) AS CANT_MVCAR FROM EXT.EXT_MOVIMIENTO_CARTERA_CREDITO_HIST MVCAR GROUP BY MVCAR.BATCHNAME) MVCAR
        ON COALESCE(CARTERA.MODIF_SOURCE,MVFID.BATCHNAME) = MVCAR.BATCHNAME
    WHERE COALESCE(CARTERA.MODIF_SOURCE, MVFID.BATCHNAME,MVCAR.BATCHNAME) = VBATCHNAME;


    /***********************************************************************/
    -- Obtener registros que no han sido traspasados
    -- EXT.EXT_MOVIMIENTO_FIANZAS_CAUCION_HIST -->  EXT.CARTERA
    /***********************************************************************/
    SELECT MVFIST.*
    FROM EXT.EXT_MOVIMIENTO_FIANZAS_CAUCION_HIST MVFIST
        LEFT OUTER JOIN EXT.CARTERA C ON MVFIST.NUM_POLIZA = C.NUM_POLIZA AND MVFIST.NUM_AVAL_FIANZA = C.NUM_FIANZA AND MVFIST.FECHA_EFECTO = C.FECHA_EFECTO
        AND MVFIST.FECHA_VENCIMIENTO = C.FECHA_VENCIMIENTO AND MVFIST.IDMEDIADOR = CONCAT(CONCAT(COD_MEDIADOR,'-'),COD_SUBCLAVE)
        AND MVFIST.BATCHNAME = C.MODIF_SOURCE
    WHERE MVFIST.BATCHNAME = VBATCHNAME
    AND C.NUM_POLIZA IS NULL AND C.NUM_FIANZA IS NULL AND C.FECHA_EFECTO IS NULL AND C.FECHA_VENCIMIENTO IS NULL AND C.COD_MEDIADOR IS NULL AND C.COD_SUBCLAVE IS NULL
    ORDER BY MVFIST.NUM_POLIZA; 


    /***********************************************************************/
    -- Obtener registros que no han sido traspasados
    -- EXT.EXT_MOVIMIENTO_CARTERA_CREDITO_HIST -->  EXT.CARTERA
    /***********************************************************************/
    SELECT MVCAR.*
    FROM EXT.EXT_MOVIMIENTO_CARTERA_CREDITO_HIST MVCAR
        LEFT OUTER JOIN EXT.CARTERA C ON MVCAR.NUM_POLIZA = C.NUM_POLIZA AND MVCAR.FECHA_EFECTO = C.FECHA_EFECTO
        AND MVCAR.FECHA_VENCIMIENTO = C.FECHA_VENCIMIENTO AND MVCAR.IDMEDIADOR = COD_MEDIADOR
        AND MVCAR.BATCHNAME = C.MODIF_SOURCE
    WHERE MVCAR.BATCHNAME = VBATCHNAME
    AND C.NUM_POLIZA IS NULL AND C.FECHA_EFECTO IS NULL AND C.FECHA_VENCIMIENTO IS NULL AND C.COD_MEDIADOR IS NULL 
    ORDER BY MVCAR.NUM_POLIZA; 

END;


CREATE COLUMN TABLE EXT.MOTIVOS_NO_TRASPASOS_SMM AS (SELECT * FROM EXT.EXT_MOVIMIENTO_CARTERA_CREDITO_HIST_SMM WHERE 1=0) ;
ALTER TABLE EXT.MOTIVOS_NO_TRASPASOS_SMM ADD(VALORHIST VARCHAR(50),VALORCARTERA VARCHAR(50));