-- BORRADO DE TABLAS
-- DROP TABLE EXT.INF_DETALLE_LIQUIDACION_RM;
-- DROP TABLE EXT.INF_LIQUIDACION_RM;

--FEBRERO
DELETE FROM EXT.CSE_DEBUG WHERE PROCESO = 'SP_INF_LIQUIDACION_RM' AND CAST(DATETIME AS DATE) = CURRENT_DATE;
CALL EXT.SP_INF_LIQUIDACION_RM('1689_COMRM_PRD_20240229_082456_RiskManagement.txt');
SELECT * FROM EXT.CSE_DEBUG WHERE PROCESO = 'SP_INF_LIQUIDACION_RM' AND CAST(DATETIME AS DATE) = CURRENT_DATE;

--MARZO
DELETE FROM EXT.CSE_DEBUG WHERE PROCESO = 'SP_INF_LIQUIDACION_RM' AND CAST(DATETIME AS DATE) = CURRENT_DATE;
CALL EXT.SP_INF_LIQUIDACION_RM('1689_COMRM_PRD_20240331_102024_RiskManagement.txt');
SELECT * FROM EXT.CSE_DEBUG WHERE PROCESO = 'SP_INF_LIQUIDACION_RM' AND CAST(DATETIME AS DATE) = CURRENT_DATE;

--ABRIL
DELETE FROM EXT.CSE_DEBUG WHERE PROCESO = 'SP_INF_LIQUIDACION_RM' AND CAST(DATETIME AS DATE) = CURRENT_DATE;
CALL EXT.SP_INF_LIQUIDACION_RM('1689_COMRM_PRD_20240430_101547_RiskManagement.txt');
SELECT * FROM EXT.CSE_DEBUG WHERE PROCESO = 'SP_INF_LIQUIDACION_RM' AND CAST(DATETIME AS DATE) = CURRENT_DATE;

--MAYO
DELETE FROM EXT.CSE_DEBUG WHERE PROCESO = 'SP_INF_LIQUIDACION_RM' AND CAST(DATETIME AS DATE) = CURRENT_DATE;
CALL EXT.SP_INF_LIQUIDACION_RM('1689_COMRM_PRD_20240531_101134_RiskManagement.txt');
SELECT * FROM EXT.CSE_DEBUG WHERE PROCESO = 'SP_INF_LIQUIDACION_RM' AND CAST(DATETIME AS DATE) = CURRENT_DATE;

--JUNIO
DELETE FROM EXT.CSE_DEBUG WHERE PROCESO = 'SP_INF_LIQUIDACION_RM' AND CAST(DATETIME AS DATE) = CURRENT_DATE;
CALL EXT.SP_INF_LIQUIDACION_RM('1689_COMRM_PRD_20240630_102431_RiskManagement.txt');
SELECT * FROM EXT.CSE_DEBUG WHERE PROCESO = 'SP_INF_LIQUIDACION_RM' AND CAST(DATETIME AS DATE) = CURRENT_DATE;

--JULIO
DELETE FROM EXT.CSE_DEBUG WHERE PROCESO = 'SP_INF_LIQUIDACION_RM' AND CAST(DATETIME AS DATE) = CURRENT_DATE;
CALL EXT.SP_INF_LIQUIDACION_RM('1689_COMRM_PRD_20240731_103207_RiskManagement.txt	');
SELECT * FROM EXT.CSE_DEBUG WHERE PROCESO = 'SP_INF_LIQUIDACION_RM' AND CAST(DATETIME AS DATE) = CURRENT_DATE;

--AGOSTO
DELETE FROM EXT.CSE_DEBUG WHERE PROCESO = 'SP_INF_LIQUIDACION_RM' AND CAST(DATETIME AS DATE) = CURRENT_DATE;
CALL EXT.SP_INF_LIQUIDACION_RM('1689_COMRM_PRD_20240831_182623_RiskManagement.txt');
SELECT * FROM EXT.CSE_DEBUG WHERE PROCESO = 'SP_INF_LIQUIDACION_RM' AND CAST(DATETIME AS DATE) = CURRENT_DATE;

--SEPTIEMBRE
DELETE FROM EXT.CSE_DEBUG WHERE PROCESO = 'SP_INF_LIQUIDACION_RM' AND CAST(DATETIME AS DATE) = CURRENT_DATE;
CALL EXT.SP_INF_LIQUIDACION_RM('1689_COMRM_PRD_20240930_104650_RiskManagement.txt');
SELECT * FROM EXT.CSE_DEBUG WHERE PROCESO = 'SP_INF_LIQUIDACION_RM' AND CAST(DATETIME AS DATE) = CURRENT_DATE;

--OCTUBRE
DELETE FROM EXT.CSE_DEBUG WHERE PROCESO = 'SP_INF_LIQUIDACION_RM' AND CAST(DATETIME AS DATE) = CURRENT_DATE;
CALL EXT.SP_INF_LIQUIDACION_RM('1689_COMRM_PRD_20241031_092016_RiskManagement.txt');
SELECT * FROM EXT.CSE_DEBUG WHERE PROCESO = 'SP_INF_LIQUIDACION_RM' AND CAST(DATETIME AS DATE) = CURRENT_DATE;

