SELECT CODIGO_FISCAL
, CASE WHEN SUBSTRING(CODIGO_FISCAL,LENGTH(CODIGO_FISCAL)-1,1) != '-' THEN CONCAT(CONCAT(SUBSTRING(CODIGO_FISCAL,0,LENGTH(CODIGO_FISCAL)-1),'-'),RIGHT(CODIGO_FISCAL,1)) 
ELSE CODIGO_FISCAL END
from EXT.PROVEEDORES_SAPFI_SMM WHERE PAIS_ISO = 'CL';



UPDATE EXT.PROVEEDORES_SAPFI
SET ESTADO = 'PTE_ENVIO'
, USER = 'NewPortalAdmin'
, MODIF_DATE = CURRENT_TIMESTAMP
, CODIGO_FISCAL = CASE WHEN SUBSTRING(CODIGO_FISCAL,LENGTH(CODIGO_FISCAL)-1,1) != '-' THEN CONCAT(CONCAT(SUBSTRING(CODIGO_FISCAL,0,LENGTH(CODIGO_FISCAL)-1),'-'),RIGHT(CODIGO_FISCAL,1))
    ELSE CODIGO_FISCAL END
, TELEFONO = CASE WHEN (TELEFONO IS NULL OR TELEFONO = '') THEN '0' ELSE TELEFONO END
, ID_REGION = '316'
, HAY_PAGOS = 'N'
, CLAVE_BANCO = ''
, NOMBRE_BANCO = 'NO_ENCONTRADO'
, CUENTA_BANCARIA = ''
, IBAN = ''
, SWIFT_BIC = ''
, IRPF = ''
WHERE PAIS_ISO = 'CL'
AND CASEID NOT IN (924,869,1749,735,1177)


SELECT CODIGO_FISCAL, COUNT(*)
FROM EXT.PROVEEDORES_SAPFI WHERE PAIS_ISO = 'CL'
GROUP BY CODIGO_FISCAL
HAVING COUNT(*) > 1

222326990
768058342	2
771585175	3
775506334
