SELECT CODIGO_FISCAL
, CASE WHEN SUBSTRING(CODIGO_FISCAL,LENGTH(CODIGO_FISCAL)-1,1) != '-' THEN CONCAT(CONCAT(SUBSTRING(CODIGO_FISCAL,0,LENGTH(CODIGO_FISCAL)-1),'-'),RIGHT(CODIGO_FISCAL,1)) 
ELSE CODIGO_FISCAL END
from EXT.PROVEEDORES_SAPFI_SMM WHERE PAIS_ISO = 'CL';



UPDATE EXT.PROVEEDORES_SAPFI SET ESTADO = 'PTE_ENVIO', USER = 'NewPortalAdmin', MODIF_DATE = CURRENT_TIMESTAMP, 
CODIGO_FISCAL = CASE WHEN SUBSTRING(CODIGO_FISCAL,LENGTH(CODIGO_FISCAL)-1,1) != '-' THEN CONCAT(CONCAT(SUBSTRING(CODIGO_FISCAL,0,LENGTH(CODIGO_FISCAL)-1),'-'),RIGHT(CODIGO_FISCAL,1)) 
	ELSE CODIGO_FISCAL END
WHERE PAIS_ISO = 'CL';