
SELECT DISTINCT T.*,C.MODIF_SOURCE 
FROM EXT.CARTERA C
LEFT JOIN 
(
          --10
SELECT 'Traspaso Pólizas y Avales-GM-10' AS MODIF_SOURCE_T,NULL CASEID FROM DUMMY
UNION ALL --20
SELECT 'Traspaso Pólizas y Avales-GM-20' AS MODIF_SOURCE_T,NULL CASEID FROM DUMMY
UNION ALL --30
SELECT 'Traspaso Pólizas y Avales-GM-30' AS MODIF_SOURCE_T,NULL CASEID FROM DUMMY
UNION ALL --40
SELECT 'Traspaso Pólizas y Avales-GM-49' AS MODIF_SOURCE_T,NULL CASEID FROM DUMMY
UNION ALL --50
SELECT 'Traspaso Pólizas y Avales-GM-50' AS MODIF_SOURCE_T,NULL CASEID FROM DUMMY
UNION ALL --60
SELECT 'Traspaso Pólizas y Avales-GM-62' AS MODIF_SOURCE_T,NULL CASEID FROM DUMMY
UNION ALL 
SELECT 'Traspaso Pólizas y Avales-GM-63' AS MODIF_SOURCE_T,NULL CASEID FROM DUMMY
UNION ALL 
SELECT 'Traspaso Pólizas y Avales-GM-67' AS MODIF_SOURCE_T,NULL CASEID FROM DUMMY
UNION ALL 
SELECT 'Traspaso Pólizas y Avales-GM-68' AS MODIF_SOURCE_T,NULL CASEID FROM DUMMY
UNION ALL --70
SELECT 'Traspaso Pólizas y Avales-GM-73' AS MODIF_SOURCE_T,NULL CASEID FROM DUMMY
UNION ALL 
SELECT 'Traspaso Pólizas y Avales-GM-74' AS MODIF_SOURCE_T,NULL CASEID FROM DUMMY
UNION ALL 
SELECT 'Traspaso Pólizas y Avales-GM-77' AS MODIF_SOURCE_T,NULL CASEID FROM DUMMY
UNION ALL --80
SELECT 'Traspaso Pólizas y Avales-GM-86' AS MODIF_SOURCE_T,NULL CASEID FROM DUMMY
UNION ALL --90
SELECT 'Traspaso Pólizas y Avales-GM-94' AS MODIF_SOURCE_T,652 CASEID FROM DUMMY
UNION ALL 
SELECT 'Traspaso Pólizas y Avales-GM-97' AS MODIF_SOURCE_T,NULL CASEID FROM DUMMY
UNION ALL 
SELECT 'Traspaso Pólizas y Avales-GM-99' AS MODIF_SOURCE_T,NULL CASEID FROM DUMMY
UNION ALL --100 
SELECT 'Traspaso Pólizas y Avales-GM-100' AS MODIF_SOURCE_T,693 CASEID FROM DUMMY
UNION ALL 
SELECT 'Traspaso Pólizas y Avales-GM-101' AS MODIF_SOURCE_T,705 CASEID FROM DUMMY
UNION ALL 
SELECT 'Traspaso Pólizas y Avales-GM-102' AS MODIF_SOURCE_T,717 CASEID FROM DUMMY
UNION ALL 
SELECT 'Traspaso Pólizas y Avales-GM-103' AS MODIF_SOURCE_T,720 CASEID FROM DUMMY
UNION ALL 
SELECT 'Traspaso Pólizas y Avales-GM-104' AS MODIF_SOURCE_T,748 CASEID FROM DUMMY
UNION ALL 
SELECT 'Traspaso Pólizas y Avales-GM-105' AS MODIF_SOURCE_T,756 CASEID FROM DUMMY
UNION ALL --130
SELECT 'Traspaso Pólizas y Avales-GM-139' AS MODIF_SOURCE_T,1007 CASEID FROM DUMMY
UNION ALL --140
SELECT 'Traspaso Pólizas y Avales-GM-140' AS MODIF_SOURCE_T,1008 CASEID FROM DUMMY
UNION ALL 
SELECT 'Traspaso Pólizas y Avales-GM-142' AS MODIF_SOURCE_T,1010 CASEID FROM DUMMY
UNION ALL 
SELECT 'Traspaso Pólizas y Avales-GM-143' AS MODIF_SOURCE_T,1011 CASEID FROM DUMMY
UNION ALL 
SELECT 'Traspaso Pólizas y Avales-GM-144' AS MODIF_SOURCE_T,1012 CASEID FROM DUMMY
UNION ALL 
SELECT 'Traspaso Pólizas y Avales-GM-145' AS MODIF_SOURCE_T,1013 CASEID FROM DUMMY
UNION ALL 
SELECT 'Traspaso Pólizas y Avales-GM-146' AS MODIF_SOURCE_T,1014 CASEID FROM DUMMY
UNION ALL 
SELECT 'Traspaso Pólizas y Avales-GM-147' AS MODIF_SOURCE_T,1015 CASEID FROM DUMMY
UNION ALL 
SELECT 'Traspaso Pólizas y Avales-GM-148' AS MODIF_SOURCE_T,1025 CASEID FROM DUMMY
UNION ALL 
SELECT 'Traspaso Pólizas y Avales-GM-149' AS MODIF_SOURCE_T,1026 CASEID FROM DUMMY
UNION ALL --150
SELECT 'Traspaso Pólizas y Avales-GM-150' AS MODIF_SOURCE_T,1027 CASEID FROM DUMMY
UNION ALL 
SELECT 'Traspaso Pólizas y Avales-GM-151' AS MODIF_SOURCE_T,1028 CASEID FROM DUMMY
UNION ALL 
SELECT 'Traspaso Pólizas y Avales-GM-152' AS MODIF_SOURCE_T,1029 CASEID FROM DUMMY
UNION ALL 
SELECT 'Traspaso Pólizas y Avales-GM-153' AS MODIF_SOURCE_T,1030 CASEID FROM DUMMY
UNION ALL 
SELECT 'Traspaso Pólizas y Avales-GM-154' AS MODIF_SOURCE_T,1031 CASEID FROM DUMMY
UNION ALL 
SELECT 'Traspaso Pólizas y Avales-GM-155' AS MODIF_SOURCE_T,1032 CASEID FROM DUMMY
UNION ALL 
SELECT 'Traspaso Pólizas y Avales-GM-156' AS MODIF_SOURCE_T,1033 CASEID FROM DUMMY
UNION ALL 
SELECT 'Traspaso Pólizas y Avales-GM-157' AS MODIF_SOURCE_T,1034 CASEID FROM DUMMY
UNION ALL 
SELECT 'Traspaso Pólizas y Avales-GM-158' AS MODIF_SOURCE_T,1035 CASEID FROM DUMMY
UNION ALL 
SELECT 'Traspaso Pólizas y Avales-GM-159' AS MODIF_SOURCE_T,1036 CASEID FROM DUMMY
UNION ALL --160
SELECT 'Traspaso Pólizas y Avales-GM-162' AS MODIF_SOURCE_T,1039 CASEID FROM DUMMY
UNION ALL 
SELECT 'Traspaso Pólizas y Avales-GM-164' AS MODIF_SOURCE_T,1041 CASEID FROM DUMMY
UNION ALL 
SELECT 'Traspaso Pólizas y Avales-GM-166' AS MODIF_SOURCE_T,1044 CASEID FROM DUMMY
UNION ALL 
SELECT 'Traspaso Pólizas y Avales-GM-167' AS MODIF_SOURCE_T,1045 CASEID FROM DUMMY
UNION ALL 
SELECT 'Traspaso Pólizas y Avales-GM-168' AS MODIF_SOURCE_T,1061 CASEID FROM DUMMY
UNION ALL --210
SELECT 'Traspaso Pólizas y Avales-GM-214' AS MODIF_SOURCE_T,1146 CASEID FROM DUMMY
UNION ALL --220
SELECT 'Traspaso Pólizas y Avales-GM-228' AS MODIF_SOURCE_T,1237 CASEID FROM DUMMY
UNION ALL 
SELECT 'Traspaso Pólizas y Avales-GM-229' AS MODIF_SOURCE_T,1249 CASEID FROM DUMMY
UNION ALL --230
SELECT 'Traspaso Pólizas y Avales-GM-232' AS MODIF_SOURCE_T,1318 CASEID FROM DUMMY
UNION ALL 
SELECT 'Traspaso Pólizas y Avales-GM-234' AS MODIF_SOURCE_T,1323 CASEID FROM DUMMY
UNION ALL 
SELECT 'Traspaso Pólizas y Avales-GM-235' AS MODIF_SOURCE_T,1332 CASEID FROM DUMMY
UNION ALL 
SELECT 'Traspaso Pólizas y Avales-GM-236' AS MODIF_SOURCE_T,1333 CASEID FROM DUMMY
UNION ALL --240
SELECT 'Traspaso Pólizas y Avales-GM-247' AS MODIF_SOURCE_T,1400 CASEID FROM DUMMY
UNION ALL --260
SELECT 'Traspaso Pólizas y Avales-GM-266' AS MODIF_SOURCE_T,1523 CASEID FROM DUMMY
UNION ALL 
SELECT 'Traspaso Pólizas y Avales-GM-267' AS MODIF_SOURCE_T,1533 CASEID FROM DUMMY
UNION ALL --270
SELECT 'Traspaso Pólizas y Avales-GM-270' AS MODIF_SOURCE_T,1556 CASEID FROM DUMMY
UNION ALL --350
SELECT 'Traspaso Pólizas y Avales-GM-359' AS MODIF_SOURCE_T,1975 CASEID FROM DUMMY
UNION ALL --360
SELECT 'Traspaso Pólizas y Avales-GM-368' AS MODIF_SOURCE_T,2059 CASEID FROM DUMMY
UNION ALL --390
SELECT 'Traspaso Pólizas y Avales-GM-391' AS MODIF_SOURCE_T,2179 CASEID FROM DUMMY
UNION ALL 
SELECT 'Traspaso Pólizas y Avales-GM-395' AS MODIF_SOURCE_T,2217 CASEID FROM DUMMY
UNION ALL 
SELECT 'Traspaso Pólizas y Avales-GM-399' AS MODIF_SOURCE_T,2289 CASEID FROM DUMMY
UNION ALL --400
SELECT 'Traspaso Pólizas y Avales-GM-400' AS MODIF_SOURCE_T,NULL CASEID FROM DUMMY
UNION ALL 
SELECT 'Traspaso Pólizas y Avales-GM-409' AS MODIF_SOURCE_T,NULL CASEID FROM DUMMY
UNION ALL --410
SELECT 'Traspaso Pólizas y Avales-GM-416' AS MODIF_SOURCE_T,NULL CASEID FROM DUMMY
UNION ALL 
SELECT 'Traspaso Pólizas y Avales-GM-417' AS MODIF_SOURCE_T,NULL CASEID FROM DUMMY
UNION ALL --420
SELECT 'Traspaso Pólizas y Avales-GM-420' AS MODIF_SOURCE_T,NULL CASEID FROM DUMMY
UNION ALL 
SELECT 'Traspaso Pólizas y Avales-GM-422' AS MODIF_SOURCE_T,NULL CASEID FROM DUMMY
UNION ALL 
SELECT 'Traspaso Pólizas y Avales-GM-426' AS MODIF_SOURCE_T,NULL CASEID FROM DUMMY
UNION ALL --440
SELECT 'Traspaso Pólizas y Avales-GM-443' AS MODIF_SOURCE_T,NULL CASEID FROM DUMMY
UNION ALL --450
SELECT 'Traspaso Pólizas y Avales-GM-450' AS MODIF_SOURCE_T,NULL CASEID FROM DUMMY
UNION ALL --500
SELECT 'Traspaso Pólizas y Avales-GM-500' AS MODIF_SOURCE_T,NULL CASEID FROM DUMMY
UNION ALL --510
SELECT 'Traspaso Pólizas y Avales-GM-510' AS MODIF_SOURCE_T,NULL CASEID FROM DUMMY
UNION ALL --520
SELECT 'Traspaso Pólizas y Avales-GM-528' AS MODIF_SOURCE_T,NULL CASEID FROM DUMMY
UNION ALL --530
SELECT 'Traspaso Pólizas y Avales-GM-533' AS MODIF_SOURCE_T,NULL CASEID FROM DUMMY
UNION ALL
SELECT 'Traspaso Pólizas y Avales-GM-537' AS MODIF_SOURCE_T,NULL CASEID FROM DUMMY
UNION ALL --540
SELECT 'Traspaso Pólizas y Avales-GM-540' AS MODIF_SOURCE_T,NULL CASEID FROM DUMMY
UNION ALL --550
SELECT 'Traspaso Pólizas y Avales-GM-550' AS MODIF_SOURCE_T,NULL CASEID FROM DUMMY
UNION ALL
SELECT 'Traspaso Pólizas y Avales-GM-552' AS MODIF_SOURCE_T,NULL CASEID FROM DUMMY
UNION ALL
SELECT 'Traspaso Pólizas y Avales-GM-556' AS MODIF_SOURCE_T,NULL CASEID FROM DUMMY
UNION ALL
SELECT 'Traspaso Pólizas y Avales-GM-559' AS MODIF_SOURCE_T,NULL CASEID FROM DUMMY
UNION ALL --560
SELECT 'Traspaso Pólizas y Avales-GM-560' AS MODIF_SOURCE_T,NULL CASEID FROM DUMMY
UNION ALL --570
SELECT 'Traspaso Pólizas y Avales-GM-570' AS MODIF_SOURCE_T,NULL CASEID FROM DUMMY
UNION ALL --580
SELECT 'Traspaso Pólizas y Avales-GM-582' AS MODIF_SOURCE_T,NULL CASEID FROM DUMMY
UNION ALL
SELECT 'Traspaso Pólizas y Avales-GM-583' AS MODIF_SOURCE_T,NULL CASEID FROM DUMMY
UNION ALL
SELECT 'Traspaso Pólizas y Avales-GM-588' AS MODIF_SOURCE_T,NULL CASEID FROM DUMMY
UNION ALL --590
SELECT 'Traspaso Pólizas y Avales-GM-591' AS MODIF_SOURCE_T,NULL CASEID FROM DUMMY
UNION ALL
SELECT 'Traspaso Pólizas y Avales-GM-596' AS MODIF_SOURCE_T,NULL CASEID FROM DUMMY
UNION ALL --600
SELECT 'Traspaso Pólizas y Avales-GM-600' AS MODIF_SOURCE_T,NULL CASEID FROM DUMMY
UNION ALL
SELECT 'Traspaso Pólizas y Avales-GM-602' AS MODIF_SOURCE_T,NULL CASEID FROM DUMMY
UNION ALL --610
SELECT 'Traspaso Pólizas y Avales-GM-610' AS MODIF_SOURCE_T,NULL CASEID FROM DUMMY
UNION ALL
SELECT 'Traspaso Pólizas y Avales-GM-611' AS MODIF_SOURCE_T,NULL CASEID FROM DUMMY
UNION ALL
SELECT 'Traspaso Pólizas y Avales-GM-614' AS MODIF_SOURCE_T,NULL CASEID FROM DUMMY
UNION ALL --620
SELECT 'Traspaso Pólizas y Avales-GM-626' AS MODIF_SOURCE_T,NULL CASEID FROM DUMMY
UNION ALL --630
SELECT 'Traspaso Pólizas y Avales-GM-633' AS MODIF_SOURCE_T,NULL CASEID FROM DUMMY
UNION ALL
SELECT 'Traspaso Pólizas y Avales-GM-637' AS MODIF_SOURCE_T,NULL CASEID FROM DUMMY
UNION ALL --640
SELECT 'Traspaso Pólizas y Avales-GM-640' AS MODIF_SOURCE_T,NULL CASEID FROM DUMMY
UNION ALL --650
SELECT 'Traspaso Pólizas y Avales-GM-650' AS MODIF_SOURCE_T,NULL CASEID FROM DUMMY
UNION ALL
SELECT 'Traspaso Pólizas y Avales-GM-652' AS MODIF_SOURCE_T,NULL CASEID FROM DUMMY
UNION ALL
SELECT 'Traspaso Pólizas y Avales-GM-656' AS MODIF_SOURCE_T,NULL CASEID FROM DUMMY
UNION ALL
SELECT 'Traspaso Pólizas y Avales-GM-659' AS MODIF_SOURCE_T,NULL CASEID FROM DUMMY
UNION ALL --660
SELECT 'Traspaso Pólizas y Avales-GM-660' AS MODIF_SOURCE_T,NULL CASEID FROM DUMMY
UNION ALL --670
SELECT 'Traspaso Pólizas y Avales-GM-670' AS MODIF_SOURCE_T,NULL CASEID FROM DUMMY
UNION ALL --680
SELECT 'Traspaso Pólizas y Avales-GM-682' AS MODIF_SOURCE_T,NULL CASEID FROM DUMMY
UNION ALL
SELECT 'Traspaso Pólizas y Avales-GM-683' AS MODIF_SOURCE_T,NULL CASEID FROM DUMMY
UNION ALL
SELECT 'Traspaso Pólizas y Avales-GM-688' AS MODIF_SOURCE_T,NULL CASEID FROM DUMMY
UNION ALL --690
SELECT 'Traspaso Pólizas y Avales-GM-691' AS MODIF_SOURCE_T,NULL CASEID FROM DUMMY
UNION ALL
SELECT 'Traspaso Pólizas y Avales-GM-696' AS MODIF_SOURCE_T,NULL CASEID FROM DUMMY
) T ON C.MODIF_SOURCE = T.MODIF_SOURCE_T
WHERE 1=1
AND NUM_POLIZA BETWEEN 0 AND 1000000
AND RAMO = 'CREDITO'
AND UPPER(MODIF_SOURCE) LIKE '%TRASPASO%'
AND ACTIVO > 0
--AND COD_MEDIADOR = '3121'
--AND MODIF_SOURCE_T IS NULL
AND (MODIF_SOURCE_T IS NULL OR UPPER(MODIF_SOURCE_T) LIKE '%TRASPASO%') AND CASEID IS NULL
ORDER BY MODIF_SOURCE


--SELECT * FROM EXT.SOLICITUD_TRASPASO WHERE CASEID = 705