DO BEGIN
UPDATE EXT.CARTERA SET FECHA_INICIO_OPESP = NULL, FECHA_FIN_OPESP = NULL;
IF NOT EXISTS (
        SELECT 1
        FROM SYS.TABLE_COLUMNS
        WHERE SCHEMA_NAME = 'EXT'
          AND TABLE_NAME = 'CARTERA'
          AND COLUMN_NAME = 'FECHA_INICIO_OPESP'
    ) THEN
        EXECUTE IMMEDIATE 'ALTER TABLE "EXT"."CARTERA" ADD ("FECHA_INICIO_OPESP" DATE)';
    END IF;
    
IF NOT EXISTS (
        SELECT 1
        FROM SYS.TABLE_COLUMNS
        WHERE SCHEMA_NAME = 'EXT'
          AND TABLE_NAME = 'CARTERA'
          AND COLUMN_NAME = 'FECHA_FIN_OPESP'
    ) THEN
        EXECUTE IMMEDIATE 'ALTER TABLE "EXT"."CARTERA" ADD ("FECHA_FIN_OPESP" DATE)';
    END IF;

DELETE FROM EXT.CSE_DEBUG WHERE PROCESO = 'SP_REVISION_CARTERA' AND CAST(DATETIME AS DATE) = CURRENT_DATE; 

CALL EXT.SP_REVISION_CARTERA;

SELECT * FROM EXT.CSE_DEBUG WHERE PROCESO = 'SP_REVISION_CARTERA'  AND CAST(DATETIME AS DATE) = CURRENT_DATE; 


SELECT NUM_POLIZA,NUM_ANUALIDAD,FECHA_INICIO,FECHA_FIN,FECHA_EFECTO,P_ESPECIAL_EMISION,P_ESPECIAL_RENOVACION,FECHA_INICIO_OPESP,* FROM EXT.CARTERA
where num_poliza = 19020 ORDER BY 1,2;

SELECT NUM_POLIZA,NUM_ANUALIDAD,FECHA_INICIO,FECHA_FIN,P_ESPECIAL_EMISION,P_ESPECIAL_RENOVACION,FECHA_EFECTO,FECHA_VENCIMIENTO,FECHA_INICIO_OPESP,FECHA_FIN_OPESP,MODIF_USER,ACTIVO,*
FROM EXT.CARTERA 
WHERE 1=1 --NUM_POLIZA IN (SELECT NUM_POLIZA FROM EXT.CARTERA WHERE (P_ESPECIAL_EMISION IS NOT NULL OR P_ESPECIAL_RENOVACION IS NOT NULL) AND RAMO = 'CREDITO')
AND NUM_POLIZA IN (10314,19020, 20502)
ORDER BY 1,2
;

END;