DELETE FROM EXT.CSE_DEBUG WHERE PROCESO = 'SP_REVISION_CARTERA' AND CAST(DATETIME AS DATE) = CURRENT_DATE; 

CALL EXT.SP_REVISION_CARTERA;

SELECT * FROM EXT.CSE_DEBUG WHERE PROCESO = 'SP_REVISION_CARTERA'  AND CAST(DATETIME AS DATE) = CURRENT_DATE; 

SELECT * FROM EXT.CARTERA_OBJ_TEMP WHERE MODIF_CASE LIKE 'CASO 0.1%' ORDER BY NUM_POLIZA;
SELECT * FROM EXT.CARTERA_OBJ_TEMP WHERE MODIF_CASE LIKE 'CASO 1.0%' ORDER BY NUM_POLIZA;
SELECT * FROM EXT.CARTERA_OBJ_TEMP WHERE MODIF_CASE LIKE 'CASO 1.1%' ORDER BY NUM_POLIZA;
SELECT * FROM EXT.CARTERA_OBJ_TEMP WHERE MODIF_CASE LIKE 'CASO 1.2%' ORDER BY NUM_POLIZA;

SELECT * FROM EXT.CARTERA_OBJ_TEMP WHERE MODIF_CASE LIKE 'CASO 0.2%' ORDER BY NUM_POLIZA;
SELECT * FROM EXT.CARTERA_OBJ_TEMP WHERE MODIF_CASE LIKE 'CASO 2.0%' ORDER BY NUM_POLIZA;
SELECT * FROM EXT.CARTERA_OBJ_TEMP WHERE MODIF_CASE LIKE 'CASO 2.1%' ORDER BY NUM_POLIZA;
SELECT * FROM EXT.CARTERA_OBJ_TEMP WHERE MODIF_CASE LIKE 'CASO 2.2%' ORDER BY NUM_POLIZA;

SELECT * FROM EXT.CARTERA_OBJ_TEMP WHERE MODIF_CASE LIKE 'CASO 0.3%' ORDER BY NUM_POLIZA;
SELECT * FROM EXT.CARTERA_OBJ_TEMP WHERE MODIF_CASE LIKE 'CASO 3.0%' ORDER BY NUM_POLIZA;
SELECT * FROM EXT.CARTERA_OBJ_TEMP WHERE MODIF_CASE LIKE 'CASO 3.1%' ORDER BY NUM_POLIZA;
SELECT * FROM EXT.CARTERA_OBJ_TEMP WHERE MODIF_CASE LIKE 'CASO 3.2%' ORDER BY NUM_POLIZA;

SELECT * FROM EXT.CARTERA_OBJ_TEMP WHERE MODIF_CASE LIKE 'CASO 0.4%' ORDER BY NUM_POLIZA;
SELECT * FROM EXT.CARTERA_OBJ_TEMP WHERE MODIF_CASE LIKE 'CASO 4.0%' ORDER BY NUM_POLIZA;
SELECT * FROM EXT.CARTERA_OBJ_TEMP WHERE MODIF_CASE LIKE 'CASO 4.1%' ORDER BY NUM_POLIZA;
SELECT * FROM EXT.CARTERA_OBJ_TEMP WHERE MODIF_CASE LIKE 'CASO 4.2%' ORDER BY NUM_POLIZA;