DO BEGIN
	DECLARE NPOLIZA BIGINT := 9142742;
	
	SELECT NUM_POLIZA,COD_MEDIADOR,COD_SUBCLAVE,* FROM EXT.CARTERA WHERE NUM_POLIZA = NPOLIZA;
	SELECT NUM_POLIZA,POSITIONNAME,FEC_INI,FEC_FIN,* FROM EXT.RELASUJE_20241023 WHERE NUM_POLIZA = LPAD(NPOLIZA,8,0);
	
	SELECT * FROM EXT.CARTERA_OBJ_TEMP WHERE NUM_POLIZA = NPOLIZA;
	
END;