SELECT NUM_ANUALIDAD, ACTIVO, IDPAIS, IDPRODUCT, NUM_POLIZA, NUM_FIANZA, FECHA_EFECTO, FECHA_VENCIMIENTO, 
COD_MEDIADOR, COD_SUBCLAVE, P_INTERMEDIACION, FECHA_INICIO, FECHA_FIN, P_ESPECIAL_EMISION, P_ESPECIAL_RENOVACION, 
NOMBRE_TOMADOR, MODIF_SOURCE, MODIF_USER, createdate, FECHA_EFECTO_TRASPASO FROM EXT.CARTERA WHERE NUM_POLIZA = 9127017


UPDATE EXT.CARTERA SET COD_MEDIADOR = 4817 WHERE NUM_POLIZA = 9127017 AND NUM_ANUALIDAD = 8

UPDATE  EXT.CARTERA  SET ACTIVO = 0 WHERE NUM_POLIZA = 9127017 AND  NUM_ANUALIDAD = 7 AND ACTIVO = 2


SELECT * FROM EXT.EXT_MOVIMIENTO_RECIBOS_HIST WHERE COD_OPERACION LIKE '%9127017%' AND ESTADOREG = 'ENVIADA' AND NUM_PERIODO = 8

CALL EXT.SP_REPROCESO_MOVIMIENTO_RECIBOS('1130540, 1132322, 1135215, 1136584')