CREATE OR REPLACE FUNCTION EXT.GET_POLIZAS_CAUCION_ERROR() 
/*
	----------------------------------------------------------------------------------------------- 
	| Author: Samuel Miralles Manresa 
	| Company: Inycom 
	| Initial Version Date: 27-11-2024 
	|---------------------------------------------------------------------------------------------- 
	| fichero MVFID
    | Muestra los registros que no existen en cartera
	| 
	| v01: versión inicial	
	| v02: SMM 20260123 Contemplar expedientes
	| v03: SMM 20260211 No avisar de errores en expedientes
	| v04: SMM 20260324 Control si existe mediador o está dado de baja
	| 
	|
	----------------------------------------------------------------------------------------------- 
*/

	RETURNS TABLE (
		MOTIVO NVARCHAR(250)
		, IDMODALIDAD SMALLINT
		, NUM_POLIZA BIGINT
		, NUM_FIANZA BIGINT
		, IDMEDIADOR NVARCHAR(20)
		, FECHA_EFECTO DATE
		, FECHA_VENCIMIENTO DATE
		, FECHA_INICIO DATE
		, FECHA_FIN DATE
		, BATCHNAME NVARCHAR(250)
	) LANGUAGE SQLSCRIPT 
	AS
	BEGIN
		RETURN SELECT CASE
			WHEN NOT EXISTS(SELECT 1 FROM EXT.MODIFICAR_MEDIADOR MM WHERE MM.POSITIONNAME = M.IDMEDIADOR)
						THEN 'NO EXISTE MEDIADOR'
			WHEN NOT EXISTS(SELECT 1 FROM EXT.MODIFICAR_MEDIADOR MM WHERE MM.POSITIONNAME = M.IDMEDIADOR
				AND COALESCE(TERMINATIONDATE,'2200-01-01') = '2200-01-01')
						THEN 'MEDIADOR DADO DE BAJA'
			WHEN M.NUM_AVAL_FIANZA IS NOT NULL AND NOT EXISTS(SELECT 1 FROM EXT.CARTERA WHERE RAMO = 'CAUCION' AND ACTIVO > 0 AND NUM_POLIZA = M.NUM_POLIZA) THEN 'PÓLIZA AVAL NO REGISTRADA EN CARTERA'
			WHEN M.NUM_AVAL_FIANZA IS NULL AND NOT EXISTS(SELECT 1 FROM EXT.CARTERA WHERE RAMO = 'CAUCION' AND ACTIVO > 0 AND NUM_POLIZA = M.NUM_POLIZA) THEN 'PÓLIZA EXPEDIENTE NO REGISTRADA EN CARTERA'
			WHEN M.NUM_AVAL_FIANZA IS NOT NULL AND NOT EXISTS(SELECT 1 FROM EXT.CARTERA WHERE RAMO = 'CAUCION' AND ACTIVO > 0 AND NUM_POLIZA = M.NUM_POLIZA AND COALESCE(NUM_FIANZA,-1) = COALESCE(M.NUM_AVAL_FIANZA,-1)) THEN 'FIANZA NO REGISTRADA EN CARTERA'
					WHEN NOT EXISTS(SELECT 1 FROM EXT.CARTERA WHERE RAMO = 'CAUCION' AND ACTIVO > 0 AND NUM_POLIZA = M.NUM_POLIZA AND COALESCE(NUM_FIANZA,-1) = COALESCE(M.NUM_AVAL_FIANZA,-1)
						AND M.IDMEDIADOR = LPAD(COD_MEDIADOR,4,0)||'-'|| LPAD(COD_SUBCLAVE,4,0)) THEN 'MEDIADOR AVAL DISTINTO EN CARTERA'
			WHEN M.NUM_AVAL_FIANZA IS NULL AND NOT EXISTS(SELECT 1 FROM EXT.CARTERA WHERE RAMO = 'CAUCION' AND ACTIVO > 0 AND NUM_POLIZA = M.NUM_POLIZA AND COALESCE(NUM_FIANZA,-1) = COALESCE(M.NUM_AVAL_FIANZA,-1)) THEN 'FIANZA NO REGISTRADA EN CARTERA'
					WHEN NOT EXISTS(SELECT 1 FROM EXT.CARTERA WHERE RAMO = 'CAUCION' AND ACTIVO > 0 AND NUM_POLIZA = M.NUM_POLIZA AND COALESCE(NUM_FIANZA,-1) = COALESCE(M.NUM_AVAL_FIANZA,-1)
						AND M.IDMEDIADOR = LPAD(COD_MEDIADOR,4,0)||'-'|| LPAD(COD_SUBCLAVE,4,0)) THEN 'MEDIADOR EXPEDIENTE DISTINTO EN CARTERA'
			WHEN M.NUM_AVAL_FIANZA IS NOT NULL AND NOT EXISTS(SELECT 1 FROM EXT.CARTERA WHERE RAMO = 'CAUCION' AND ACTIVO > 0 AND NUM_POLIZA = M.NUM_POLIZA AND COALESCE(NUM_FIANZA,-1) = COALESCE(M.NUM_AVAL_FIANZA,-1)
						AND M.IDMEDIADOR = LPAD(COD_MEDIADOR,4,0)||'-'|| LPAD(COD_SUBCLAVE,4,0) 
						AND M.FECHA_EFECTO = FECHA_EFECTO
						
					) THEN 'FECHA EFECTO AVAL DISTINTA EN CARTERA' 
			WHEN M.NUM_AVAL_FIANZA IS  NULL AND NOT EXISTS(SELECT 1 FROM EXT.CARTERA WHERE RAMO = 'CAUCION' AND ACTIVO > 0 AND NUM_POLIZA = M.NUM_POLIZA AND COALESCE(NUM_FIANZA,-1) = COALESCE(M.NUM_AVAL_FIANZA,-1)
						AND M.IDMEDIADOR = LPAD(COD_MEDIADOR,4,0)||'-'|| LPAD(COD_SUBCLAVE,4,0) 
						AND M.FECHA_EFECTO = FECHA_EFECTO
						
					) THEN 'FECHA EFECTO EXPEDIENTE DISTINTA EN CARTERA' 
			WHEN M.NUM_AVAL_FIANZA IS NOT NULL AND NOT EXISTS(SELECT 1 FROM EXT.CARTERA WHERE RAMO = 'CAUCION' AND ACTIVO > 0 AND NUM_POLIZA = M.NUM_POLIZA AND COALESCE(NUM_FIANZA,-1) = COALESCE(M.NUM_AVAL_FIANZA,-1)
						AND M.IDMEDIADOR = LPAD(COD_MEDIADOR,4,0)||'-'|| LPAD(COD_SUBCLAVE,4,0) 
						AND M.FECHA_EFECTO = FECHA_EFECTO
						AND M.FECHA_VENCIMIENTO = FECHA_VENCIMIENTO
						
					) THEN 'FECHA VENCIMIENTO AVAL DISTINTA EN CARTERA' 
			WHEN M.NUM_AVAL_FIANZA IS  NULL AND NOT EXISTS(SELECT 1 FROM EXT.CARTERA WHERE RAMO = 'CAUCION' AND ACTIVO > 0 AND NUM_POLIZA = M.NUM_POLIZA AND COALESCE(NUM_FIANZA,-1) = COALESCE(M.NUM_AVAL_FIANZA,-1)
						AND M.IDMEDIADOR = LPAD(COD_MEDIADOR,4,0)||'-'|| LPAD(COD_SUBCLAVE,4,0) 
						AND M.FECHA_EFECTO = FECHA_EFECTO
						AND M.FECHA_VENCIMIENTO = FECHA_VENCIMIENTO
						
					) THEN 'FECHA EFECTO EXPEDIENTE DISTINTA EN CARTERA' 
			ELSE 'OK. EXISTE EN CARTERA' END  AS MOTIVO
		, M.IDMODALIDAD
		, M.NUM_POLIZA
		, M.NUM_AVAL_FIANZA AS NUM_FIANZA
		, M.IDMEDIADOR
		, M.FECHA_EFECTO
		, M.FECHA_VENCIMIENTO
		, M.FECHA_INI_COBERTURA AS FECHA_INICIO
		, M.FECHA_FIN_COBERTURA AS FECHA_FIN
		, M.BATCHNAME
		FROM EXT.EXT_MOVIMIENTO_FIANZAS_CAUCION_HIST M
			WHERE M.BATCHNAME IN (SELECT BATCHNAME FROM EXT.REGISTRO_INTERFACES WHERE NOTIFICATION = 0 
				AND BATCHNAME LIKE '%MVFID%' AND STATUS = 'SUCCESS')
			AND NOT EXISTS (SELECT 1 FROM EXT.CARTERA WHERE RAMO = 'CAUCION' AND ACTIVO > 0 AND NUM_POLIZA = M.NUM_POLIZA AND COALESCE(NUM_FIANZA,-1) = COALESCE(M.NUM_AVAL_FIANZA,-1)
						AND M.IDMEDIADOR = LPAD(COD_MEDIADOR,4,0)||'-'|| LPAD(COD_SUBCLAVE,4,0) 
						-- AND M.FECHA_EFECTO = FECHA_EFECTO AND M.FECHA_VENCIMIENTO = FECHA_VENCIMIENTO
						AND 1 = (CASE WHEN NUM_FIANZA IS NOT NULL THEN CASE WHEN M.FECHA_EFECTO = FECHA_EFECTO THEN 1 ELSE 0 END ELSE 1 END)
						AND 1 = (CASE WHEN NUM_FIANZA IS NOT NULL THEN CASE WHEN M.FECHA_VENCIMIENTO = FECHA_VENCIMIENTO THEN 1 ELSE 0 END ELSE 1 END)
			)
		;
		
		
	END