CREATE COLUMN TABLE "EXT"."CARGA_POLIZAS_TOMADOR_HIST"(
	"ID_SALESFORCE" NVARCHAR(15),
	"EXTERNALID" NVARCHAR(15),
	"NUM_POLIZA" NVARCHAR(10),
	"MODALIDAD" NVARCHAR(3),
	"TOMADOR" NVARCHAR(250),
	"FECHA_EFECTO" NVARCHAR(10),
	"FECHA_FINAL_CONTRATO" NVARCHAR(10),
	"FASE" NVARCHAR(10),
	"ESTADO" NVARCHAR(25),
	"PROPIETARIO" NVARCHAR(250),
	"CUENTA_MEDIADORA" NVARCHAR(250),
	"GERENTE_CESCE" NVARCHAR(50),
	"BATCHNAME" NVARCHAR(250),
	"CREATEDATE" TIMESTAMP
	
)
UNLOAD PRIORITY 5 AUTO MERGE;
