
CREATE VIEW EXT.CSA_INF_LIQUIDACION_RM_SVW(
			CODIGO,
	    	MEDIADOR,
			IDRECIBO,
	    	IDPAIS,
	    	SOCIEDAD,
	    	CONCEPTO,
	    	FECHA_RECIBO_LIQUIDACION,
	    	ESTADO,
	    	REFERENCIA,
	    	FECHA_FACTURA,
	    	IDDIVISA,
	    	MONEDA,
	    	IMPORTE,
	    	PERIODSEQ
		) AS 
		SELECT CODIGO,
	    	MEDIADOR,
			IDRECIBO,
	    	IDPAIS,
	    	SOCIEDAD,
	    	CONCEPTO,
	    	FECHA_RECIBO_LIQUIDACION,
	    	ESTADO,
	    	REFERENCIA,
	    	FECHA_FACTURA,
	    	IDDIVISA,
	    	MONEDA,
	    	IMPORTE,
	    	PERIODSEQ
	    FROM EXT.INF_LIQUIDACION_RM;
	    
	   