CREATE TABLE EXT.RESPUESTA_FACTURAS_LOAD(
	PROVEEDOR VARCHAR(12),
	REFERENCIA VARCHAR(12)
);

CREATE TABLE EXT.RESPUESTA_FACTURAS(
	PROVEEDOR VARCHAR(12),
	REFERENCIA VARCHAR(12),
	BATCHNAME VARCHAR(120),
	IDFACTURA BIGINT
);