CREATE TABLE EXT.RESPUESTA_FACTURAS_LOAD(
	CRF VARCHAR(3),   
    ESTADO VARCHAR(2),
	PROVEEDOR VARCHAR(12),
	REFERENCIA VARCHAR(12),
    MENSAJE VARCHAR(120),
    PROCESO VARCHAR(120)
);

CREATE TABLE EXT.RESPUESTA_FACTURAS(
	ESTADO VARCHAR(1),
    PROVEEDOR VARCHAR(12),
	REFERENCIA VARCHAR(12),
    MENSAJE VARCHAR(120),
    PROCESO VARCHAR(120),
	BATCHNAME VARCHAR(120),
	IDFACTURA BIGINT
);


CREATE TABLE EXT.PAGO_FACTURAS_LOAD(
	CRF VARCHAR(3),   
    ESTADO VARCHAR(2),
	PROVEEDOR VARCHAR(12),
	REFERENCIA VARCHAR(12),
    MENSAJE VARCHAR(120),
    PROCESO VARCHAR(120)
);

CREATE TABLE EXT.PAGO_FACTURAS(
	ESTADO VARCHAR(1),
    PROVEEDOR VARCHAR(12),
	REFERENCIA VARCHAR(12),
    MENSAJE VARCHAR(120),
    PROCESO VARCHAR(120),
	BATCHNAME VARCHAR(120),
	IDFACTURA BIGINT
);


ALTER TABLE EXT.FACTURAS ADD(FECHA_CARGA DATE, FECHA_PAGO DATE);