CREATE COLUMN TABLE "EXT"."RELASUJE_HIST"(
	"MOD" NVARCHAR(3),
	"NUM_POLIZA" NVARCHAR(10),
	"TIP" NVARCHAR(3),
	"COD_AGENT" NVARCHAR(10),
	"NOMBRE_AGENTE" NVARCHAR(255),
	"PROVINCIA" NVARCHAR(100),
	"PAIS" NVARCHAR(3),
	"FEC_INI" NVARCHAR(10),
	"FEC_FIN" NVARCHAR(10),
	"ERROR" NVARCHAR(100),
	"NOMBRE_SUBCLAVE" NVARCHAR(50),
	"COD_SUBCLAVE" NVARCHAR(4),
	"INTERMEDIA" NVARCHAR(10),
	"POSITIONNAME" NVARCHAR(10),
    "BATCHNAME" NVARCHAR(255),
    "CREATEDATE" TIMESTAMP
)
UNLOAD PRIORITY 5 AUTO MERGE;