CREATE COLUMN TABLE "EXT"."REGISTRO_INTERFACES"(
	"BATCHNAME" VARCHAR(120) NOT NULL,
	"REV" INTEGER CS_INT DEFAULT 0 NOT NULL,
	"NUMREC" INTEGER CS_INT NOT NULL,
	"STARTTIME" LONGDATE CS_LONGDATE NOT NULL,
	"ENDTIME" LONGDATE CS_LONGDATE,
    "STATUS" VARCHAR(20),
    "ERROR" NVARCHAR(1000),
    "NOTIFICATION" SMALLINT DEFAULT 0,
    "MODIF_DATE " LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP,
    "COMMENTS" NVARCHAR(1000),
    CONSTRAINT "REGISTRO_INTERFACES_PK" PRIMARY KEY(
		"BATCHNAME",
		"REV"
	)   
)
UNLOAD PRIORITY 5 AUTO MERGE;