DO BEGIN
	select FECHA_INI,FECHA_FIN,* from ext.EXT_MOVIMIENTO_CARTERA_CREDITO_LOAD;

	select FECHA_INI,FECHA_FIN,* from ext.EXT_MOVIMIENTO_CARTERA_CREDITO_HIST_smm;
	
	CALL EXT.SP_MOVIMIENTOS_HIST_SMM('PRUEBA_MVCAR.TXT');
	
	select FECHA_INI,FECHA_FIN,* from ext.EXT_MOVIMIENTO_CARTERA_CREDITO_HIST_smm 
	WHERE BATCHNAME = 'PRUEBA_MVCAR.TXT';
END;