DO BEGIN

    --DECLARE VBATCHNAME VARCHAR(255) = '1689_MVFID_PRD_20240912_061502_MovFianzas.txt';
    DECLARE VBATCHNAME VARCHAR(255) = '1689_MVFID_PRD_20240618_1030000_MovFianzas';

    /***********************************************************************/
    -- Obtener cantidad de diferencias entre las tablas
    -- EXT.EXT_MOVIMIENTO_FIANZAS_CAUCION_HIST
    -- EXT.EXT_MOVIMIENTO_CARTERA_CREDITO_HIST
    -- EXT.CARTERA
    /***********************************************************************/
    SELECT 
        COALESCE(CARTERA.MODIF_SOURCE, MVFID.BATCHNAME,MVCAR.BATCHNAME) AS nombre_fichero,
        COALESCE(CARTERA.CANT_CARTERA, 0) AS CANT_CARTERA,
        COALESCE(MVFID.CANT_MVFID, 0) AS CANT_MVFID,
        CASE WHEN COALESCE(MVFID.CANT_MVFID, 0) = 0 THEN 0 ELSE COALESCE(MVFID.CANT_MVFID, 0) - COALESCE(CARTERA.CANT_CARTERA, 0) END AS DIF_CANT_MVFID,
        COALESCE(MVCAR.CANT_MVCAR, 0) AS CANT_MVCAR,
        CASE WHEN COALESCE(MVCAR.CANT_MVCAR, 0) = 0 THEN 0 ELSE COALESCE(MVCAR.CANT_MVCAR, 0) - COALESCE(CARTERA.CANT_CARTERA, 0) END AS DIF_CANT_MVCAR
    FROM 
        (SELECT C.MODIF_SOURCE, COUNT(*) AS CANT_CARTERA FROM EXT.CARTERA C GROUP BY C.MODIF_SOURCE) CARTERA
    FULL OUTER JOIN 
        (SELECT MVFID.BATCHNAME, COUNT(*) AS CANT_MVFID FROM EXT.EXT_MOVIMIENTO_FIANZAS_CAUCION_HIST MVFID GROUP BY MVFID.BATCHNAME) MVFID
    ON CARTERA.MODIF_SOURCE = MVFID.BATCHNAME
    FULL OUTER JOIN 
    (SELECT MVCAR.BATCHNAME, COUNT(*) AS CANT_MVCAR FROM EXT.EXT_MOVIMIENTO_CARTERA_CREDITO_HIST MVCAR GROUP BY MVCAR.BATCHNAME) MVCAR
        ON COALESCE(CARTERA.MODIF_SOURCE,MVFID.BATCHNAME) = MVCAR.BATCHNAME
    WHERE COALESCE(CARTERA.MODIF_SOURCE, MVFID.BATCHNAME,MVCAR.BATCHNAME) = VBATCHNAME;


    /***********************************************************************/
    -- Obtener registros que no han sido traspasados MVFID
    -- EXT.EXT_MOVIMIENTO_FIANZAS_CAUCION_HIST -->  EXT.CARTERA
    /***********************************************************************/
    SELECT MVFID.*
    FROM EXT.EXT_MOVIMIENTO_FIANZAS_CAUCION_HIST MVFID
        LEFT OUTER JOIN EXT.CARTERA C ON MVFID.NUM_POLIZA = C.NUM_POLIZA AND MVFID.NUM_AVAL_FIANZA = C.NUM_FIANZA AND MVFID.FECHA_EFECTO = C.FECHA_EFECTO
        AND MVFID.FECHA_VENCIMIENTO = C.FECHA_VENCIMIENTO AND MVFID.IDMEDIADOR = CONCAT(CONCAT(COD_MEDIADOR,'-'),COD_SUBCLAVE)
        AND MVFID.BATCHNAME = C.MODIF_SOURCE
    WHERE MVFID.BATCHNAME = VBATCHNAME
    AND C.NUM_POLIZA IS NULL AND C.NUM_FIANZA IS NULL AND C.FECHA_EFECTO IS NULL AND C.FECHA_VENCIMIENTO IS NULL AND C.COD_MEDIADOR IS NULL AND C.COD_SUBCLAVE IS NULL
    ORDER BY MVFID.NUM_POLIZA; 


    /***********************************************************************/
    -- Obtener registros que no han sido traspasados MVCAR
    -- EXT.EXT_MOVIMIENTO_CARTERA_CREDITO_HIST -->  EXT.CARTERA
    /***********************************************************************/
    SELECT MVCAR.*
    FROM EXT.EXT_MOVIMIENTO_CARTERA_CREDITO_HIST MVCAR
        LEFT OUTER JOIN EXT.CARTERA C ON MVCAR.NUM_POLIZA = C.NUM_POLIZA AND MVCAR.FECHA_EFECTO = C.FECHA_EFECTO
        AND MVCAR.FECHA_VENCIMIENTO = C.FECHA_VENCIMIENTO AND MVCAR.IDMEDIADOR = COD_MEDIADOR
        AND MVCAR.BATCHNAME = C.MODIF_SOURCE
    WHERE MVCAR.BATCHNAME = VBATCHNAME
    AND C.NUM_POLIZA IS NULL AND C.FECHA_EFECTO IS NULL AND C.FECHA_VENCIMIENTO IS NULL AND C.COD_MEDIADOR IS NULL 
    ORDER BY MVCAR.NUM_POLIZA; 



 
SELECT 
C_SUB.MODIF_SOURCE,
    CASE 
        WHEN C_SUB.MODIF_SOURCE IS NOT NULL 
        THEN CONCAT('EXISTE EN CARTERA CON OTRO FICHERO: ', C_SUB.MODIF_SOURCE)
        ELSE NULL
    END AS MOTIVO,
    MVFID.NUM_POLIZA,MVFID.NUM_AVAL_FIANZA,MVFID.IDMEDIADOR,
    MVFID.FECHA_EFECTO, MVFID.FECHA_VENCIMIENTO
    ,MVFID.BATCHNAME 
FROM EXT.EXT_MOVIMIENTO_FIANZAS_CAUCION_HIST MVFID
LEFT OUTER JOIN EXT.CARTERA C 
    ON MVFID.NUM_POLIZA = C.NUM_POLIZA 
    AND MVFID.NUM_AVAL_FIANZA = C.NUM_FIANZA 
    AND MVFID.FECHA_EFECTO = C.FECHA_EFECTO 
    AND MVFID.FECHA_VENCIMIENTO = C.FECHA_VENCIMIENTO 
    AND MVFID.IDMEDIADOR = CONCAT(CONCAT(C.COD_MEDIADOR, '-'), C.COD_SUBCLAVE)
    AND MVFID.BATCHNAME = C.MODIF_SOURCE
LEFT OUTER JOIN (
    SELECT 
        C_SUB.NUM_POLIZA, 
        C_SUB.NUM_FIANZA, 
        C_SUB.MODIF_SOURCE,
        C_SUB.COD_MEDIADOR,
        C_SUB.COD_SUBCLAVE
    FROM EXT.CARTERA C_SUB
) C_SUB 
    ON C_SUB.NUM_POLIZA = MVFID.NUM_POLIZA 
    AND C_SUB.NUM_FIANZA = MVFID.NUM_AVAL_FIANZA 
    AND MVFID.IDMEDIADOR = CONCAT(CONCAT(C_SUB.COD_MEDIADOR, '-'), C_SUB.COD_SUBCLAVE)
   -- AND C_SUB.MODIF_SOURCE <> MVFID.BATCHNAME
WHERE 1=1
AND MVFID.BATCHNAME = VBATCHNAME
  AND C.NUM_POLIZA IS NULL 
  AND C.NUM_FIANZA IS NULL 
  AND C.FECHA_EFECTO IS NULL 
  AND C.FECHA_VENCIMIENTO IS NULL 
  AND C.COD_MEDIADOR IS NULL 
  AND C.COD_SUBCLAVE IS NULL
--  AND MVFID.NUM_POLIZA = 1011380
ORDER BY MVFID.NUM_POLIZA;
END;


select * from ext.CARTERA  where NUM_POLIZA = 1004256 
--AND NUM_FIANZA = 55581
;