CREATE COLUMN TABLE "EXT"."PAGO_FACTURAS"(
	"IDENTIFIER" VARCHAR(26),
	"IDFACTURA" BIGINT,
	"ESTADO" VARCHAR(15),
	"FECHA_VALOR" DATE CS_DAYDATE,
	"CHECK_NUMBER" VARCHAR(40),
	"BATCHNAME" VARCHAR(250)
)
UNLOAD PRIORITY 5 AUTO MERGE;

CREATE TABLE EXT.RESPUESTA_FACTURAS(
	ESTADO VARCHAR(1),
    PROVEEDOR VARCHAR(12),
	REFERENCIA VARCHAR(12),
    MENSAJE VARCHAR(120),
    PROCESO VARCHAR(120),
	BATCHNAME VARCHAR(120),
	IDFACTURA BIGINT
);


CREATE TABLE EXT.PAGO_FACTURAS_LOAD(
	LINEA NVARCHAR(500)
);

CREATE TABLE EXT.PAGO_FACTURAS(
	LINEA NVARCHAR(500)
);


ALTER TABLE EXT.FACTURAS ADD(FECHA_CARGA DATE, FECHA_PAGO DATE);


