CREATE OR REPLACE PROCEDURE "EXT"."SP_PAGO_FACTURAS" (IN IN_FILENAME Varchar(120)) LANGUAGE SQLSCRIPT 
SQL SECURITY DEFINER DEFAULT SCHEMA "EXT" AS BEGIN 

DECLARE io_contador Number := 0;
DECLARE numLin Number := 0;
DECLARE numLineasFichero Number := 0;
DECLARE i_Tenant VARCHAR(127);
DECLARE cVersion CONSTANT VARCHAR(2) := '01';

DECLARE v_proc_name VARCHAR(50) := ::CURRENT_OBJECT_NAME;
DECLARE v_posIni INT;
DECLARE v_posFin INT;
DECLARE v_fechaPago DATE;



DECLARE i_rev Number := 0; -- Número de ejecución


-- Versiones --------------------------------------------------------------------------------------------------------
-- v01
---------------------------------------------------------------------------------------------------------------------

DECLARE EXIT HANDLER FOR SQLEXCEPTION 
BEGIN 
	
    --Actualizamos registro status = FAILED    
    UPDATE EXT.REGISTRO_INTERFACES SET NUMREC = numLineasFichero, STATUS = 'FAILED', ENDTIME = current_timestamp, ERROR = LEFT(IFNULL( ::SQL_ERROR_MESSAGE, ''),1000) WHERE BATCHNAME = IN_FILENAME AND REV = i_rev;
	
	CALL LIB_GLOBAL_CESCE :w_debug (
    	i_Tenant,
    	v_proc_name || '. SQL ERROR_MESSAGE: ' || IFNULL( ::SQL_ERROR_MESSAGE, '') || '. SQL_ERROR_CODE: ' ||  ::SQL_ERROR_CODE,
    	v_proc_name,
    	io_contador
	);
    RESIGNAL;

END;

SELECT TENANTID INTO i_Tenant
FROM CS_TENANT;

CALL LIB_GLOBAL_CESCE :w_debug(
    i_Tenant,
    'STARTING with SESSION_USER: ' || SESSION_USER || ' version ' || cVersion,
    v_proc_name,
    io_contador
);

CALL LIB_GLOBAL_CESCE :w_debug (
    i_Tenant,
    'COMIENZA Tratamiento fichero ' || IN_FILENAME,
    v_proc_name,
    io_contador
);


---------------------------------------------------------------------------------------------------------------------

---------------------------------------------------------
--Insertamos un registro en la tabla REGISTRO_INTERFACES
--Al finalizar el proceso actualizar el registro
SELECT IFNULL(MAX(REV),0) + 1 INTO i_rev FROM REGISTRO_INTERFACES WHERE BATCHNAME = IN_FILENAME;

--ELIMINAMOS REGISTROS DEL FICHERO CARGADO
DELETE FROM EXT.PAGO_FACTURAS WHERE BATCHNAME = IN_FILENAME;

SELECT count(*) into numLineasFichero
    FROM (select distinct * FROM EXT.PAGO_FACTURAS_LOAD) ;
    
--Obtenemos fecha del fichero
v_posIni := INSTR(IN_FILENAME, '_', 1, 1) + 1;
v_posFin := INSTR(IN_FILENAME, '_', 1, 2);

SELECT SUBSTR(IN_FILENAME,v_posIni,v_posFin-v_posIni) INTO  v_fechaPago FROM DUMMY;
--substr(i_ficheroTXSTA,v_posIni, v_posFin - v_posIni )

INSERT INTO REGISTRO_INTERFACES(BATCHNAME,REV,NUMREC,STARTTIME)
VALUES(IN_FILENAME, i_rev, 0,current_timestamp);

---------------------------------------------------------

INSERT INTO EXT.PAGO_FACTURAS(ESTADO,PROVEEDOR,REFERENCIA,MENSAJE,PROCESO,BATCHNAME,IDFACTURA)
SELECT ESTADO,PROVEEDOR,REFERENCIA,MENSAJE,PROCESO,IN_FILENAME,IDFACTURA
FROM EXT.PAGO_FACTURAS_LOAD RF LEFT JOIN EXT.FACTURAS F ON RF.PROVEEDOR = F.CODPROVEEDOR AND RF.REFERENCIA = F.REFFACTURA
WHERE ESTADO IN ('S','E');

IF EXISTS(SELECT 1 FROM EXT.PAGO_FACTURAS WHERE IDFACTURA IS NULL AND BATCHNAME = IN_FILENAME) THEN
	CALL LIB_GLOBAL_CESCE :w_debug (
    i_Tenant,
    'NO SE HA OBTENIDO IDFACTURA EN ALGÚN REGISTRO',
    v_proc_name,
    io_contador
);
ELSE
	
END IF;

IF EXISTS(SELECT 1 FROM EXT.PAGO_FACTURAS WHERE ESTADO = 'E' AND BATCHNAME = IN_FILENAME) THEN
	CALL LIB_GLOBAL_CESCE :w_debug (
    i_Tenant,
    'EL FICHERO CONTIENE ERRORES',
    v_proc_name,
    io_contador
);

	
ELSE
	--Actualizamos registro status = SUCCESS
	UPDATE EXT.REGISTRO_INTERFACES SET NUMREC = numLineasFichero, STATUS = 'SUCCESS', ENDTIME = current_timestamp WHERE BATCHNAME = IN_FILENAME AND REV = i_rev;
	
END IF;

UPDATE F SET FECHA_PAGO = v_fechaPago, ESTADOFACTURA = CASE WHEN RF.ESTADO = 'E' THEN 'ERROR' ELSE 'PAGADO' END, MODIF_DATE = CURRENT_TIMESTAMP 
	FROM EXT.FACTURAS F INNER JOIN EXT.PAGO_FACTURAS RF ON F.IDFACTURA = RF.IDFACTURA
	WHERE RF.BATCHNAME = IN_FILENAME;



CALL LIB_GLOBAL_CESCE :w_debug (
    i_Tenant,
    'Proceso Terminado Satisfactoriamente',
    v_proc_name,
    io_contador
);



COMMIT;

END;

DO BEGIN

DELETE FROM EXT.CSE_DEBUG WHERE CAST(DATETIME AS DATE) = CURRENT_DATE;
DELETE FROM EXT.REGISTRO_INTERFACES WHERE CAST(STARTTIME AS DATE) = CURRENT_DATE;
--TRUNCATE TABLE EXT.RESPUESTA_FACTURAS_LOAD;

-- INSERT INTO EXT.RESPUESTA_FACTURAS_LOAD (ESTADO,PROVEEDOR,REFERENCIA) VALUES ('W',NULL,NULL);
-- INSERT INTO EXT.RESPUESTA_FACTURAS_LOAD (ESTADO,PROVEEDOR,REFERENCIA) VALUES ('W','M046011345','24000002');
-- INSERT INTO EXT.RESPUESTA_FACTURAS_LOAD (ESTADO,PROVEEDOR,REFERENCIA) VALUES ('S','M046011345','24000002');
-- INSERT INTO EXT.RESPUESTA_FACTURAS_LOAD (ESTADO,PROVEEDOR,REFERENCIA) VALUES ('W','M046011345','24000002');
-- INSERT INTO EXT.RESPUESTA_FACTURAS_LOAD (ESTADO,PROVEEDOR,REFERENCIA) VALUES ('W','M048028011','240000025');
-- INSERT INTO EXT.RESPUESTA_FACTURAS_LOAD (ESTADO,PROVEEDOR,REFERENCIA) VALUES ('E','M048028011','240000025');
-- INSERT INTO EXT.RESPUESTA_FACTURAS_LOAD (ESTADO,PROVEEDOR,REFERENCIA) VALUES ('W','M048028011','240000025');
CALL EXT.SP_PAGO_FACTURAS('IF002PAGOFAC_20240513_CE01.csv');

SELECT * FROM EXT.CSE_DEBUG WHERE CAST(DATETIME AS DATE) = CURRENT_DATE;
SELECT * FROM EXT.REGISTRO_INTERFACES WHERE CAST(STARTTIME AS DATE) = CURRENT_DATE;

SELECT * FROM EXT.PAGO_FACTURAS_LOAD;
SELECT * FROM EXT.PAGO_FACTURAS;
SELECT * FROM EXT.FACTURAS WHERE IDFACTURA IN (130,513);
SELECT * FROM EXT.FACTURAS WHERE FECHA_CARGA IS NOT NULL;
END;