CREATE COLUMN TABLE "EXT"."RETORNO_CONTABILIDAD"(
	"PERIODSEQ" BIGINT CS_FIXED NOT NULL,
	"CREDITSEQ" BIGINT CS_FIXED NOT NULL,
	"POSITIONSEQ" BIGINT CS_FIXED NOT NULL,
	"POSITIONNAME" VARCHAR(10) NOT NULL,
	"ORDERID" VARCHAR(40) NOT NULL,
	"IDPRODUCT" VARCHAR(127) NOT NULL,
	"FECHADATOS" DATE CS_DAYDATE NOT NULL,
	"SOCIEDAD" NVARCHAR(4) NOT NULL,
	"PAIS" NVARCHAR(2) NOT NULL,
	"FECHA_CONTABLE" NVARCHAR(8) NOT NULL,
	"FECHA_DOCUMENTO" NVARCHAR(8) NOT NULL,
	"REFERENCIA" NVARCHAR(16),
	"TIPO_DE_MOVIMIENTO" NVARCHAR(2) NOT NULL,
	"ESTADO" NVARCHAR(1) NOT NULL,
	"INDICADOR_DE_PRIMA" NVARCHAR(1) NOT NULL,
	"RIESGO" NVARCHAR(8) NOT NULL,
	"TIPO_DE_PERSONA" NVARCHAR(2) NOT NULL,
	"TIPO_DE_MEDIADOR" SMALLINT CS_INT NOT NULL,
	"MODALIDAD" NVARCHAR(3) NOT NULL,
	"POLIZA" NVARCHAR(8) NOT NULL,
	"N_RECIBO" NVARCHAR(6) NOT NULL,
	"N_FACTURA" NVARCHAR(18) NOT NULL,
	"MONEDA" NVARCHAR(7) NOT NULL,
	"IMPORTE" DECIMAL(13, 2) CS_FIXED NOT NULL,
	"CODIGO_DE_SUJETO_CESCE" NVARCHAR(9) NOT NULL,
	"NIF" NVARCHAR(15) NOT NULL,
	"CREATEDATE" LONGDATE CS_LONGDATE NOT NULL,
	"ESTADOREG" VARCHAR(10) NOT NULL
)
UNLOAD PRIORITY 5 AUTO MERGE;


ALTER TABLE "EXT"."RETORNO_CONTABILIDAD" ADD (LINENUMBER BIGINT CS_FIXED, SUBLINENUMBER BIGINT CS_FIXED, EVENTTYPESEQ BIGINT CS_FIXED);