CREATE OR REPLACE FUNCTION EXT.GET_ANUALIDAD_OP_ESP(
	P_COD_MEDIADOR NVARCHAR(10), P_COD_SUBCLAVE NVARCHAR(10)
	, P_NUM_POLIZA NVARCHAR(25)
)
RETURNS TABLE (
     NUM_ANUALIDAD INTEGER
     , NUM_POLIZA VARCHAR(25)
     , COD_MEDIADOR VARCHAR(10)
     , COD_SUBCLAVE VARCHAR(10)
     , RAMO VARCHAR(10)
     
) 
LANGUAGE SQLSCRIPT 
AS
BEGIN
    RETURN 
        SELECT NUM_ANUALIDAD, NUM_POLIZA, COD_MEDIADOR, COD_SUBCLAVE, RAMO
        FROM EXT.CARTERA C
		WHERE C.COD_MEDIADOR = P_COD_MEDIADOR AND C.COD_SUBCLAVE = P_COD_SUBCLAVE
		AND C.RAMO = 'CREDITO' AND C.NUM_POLIZA = P_NUM_POLIZA
		AND C.ACTIVO = 1
		ORDER BY NUM_ANUALIDAD
    ; 
END;

DO BEGIN
	SELECT * FROM EXT.GET_ANUALIDAD_OP_ESP('0004','0000',22751);
END;