CREATE FUNCTION EXT.GET_MEDIADOR_RECEPTOR_RELACION_INTERMEDIACION(
	P_COD_MEDIADOR NVARCHAR(10), P_COD_SUBCLAVE NVARCHAR(10)
	, P_RAMO VARCHAR(20), P_NUM_POLIZA NVARCHAR(25)
)
RETURNS TABLE (
     COD_MEDIADOR VARCHAR(10)
     , COD_SUBCLAVE VARCHAR(10)
) 
LANGUAGE SQLSCRIPT 
AS
BEGIN
    RETURN 
        SELECT R.COD_MEDIADOR,R.COD_SUBCLAVE 
        FROM EXT.CARTERA C
		LEFT JOIN EXT.CARTERA R ON C.NUM_POLIZA = R.NUM_POLIZA AND C.NUM_ANUALIDAD = R.NUM_ANUALIDAD AND C.COD_MEDIADOR <> R.COD_MEDIADOR
		WHERE C.COD_MEDIADOR = P_COD_MEDIADOR AND C.COD_SUBCLAVE = P_COD_SUBCLAVE
		AND C.RAMO = P_RAMO
		AND R.ACTIVO = 1
    ; 
END