CREATE OR REPLACE FUNCTION EXT.GET_BUSCAR_POLIZAS(
	P_COD_MEDIADOR NVARCHAR(10), P_COD_SUBCLAVE NVARCHAR(10)
	, P_RAMO VARCHAR(20), P_TIPO_TRASPASO_CAUCION VARCHAR(20)
	, P_FECHA_TRASPASO DATE, P_NUM_POLIZA NVARCHAR(25)
    , P_MODIFICAR_RELACION INTEGER
)
RETURNS TABLE (
     RAMO VARCHAR(20)
    , IDPRODUCT NVARCHAR(127)
    , DES_PRODUCT NVARCHAR(250)
    , NUM_POLIZA NVARCHAR(25)
    , NUM_ANUALIDAD INTEGER
    --, NUM_AVAL_HOST BIGINT
    , CODIGO_AVAL BIGINT
    , NUM_FIANZA DECIMAL(30,0)
    , FECHA_INICIO DATE
    , FECHA_FIN DATE
    , NOMBRE_TOMADOR NVARCHAR(50)
    , NIF_TOMADOR NVARCHAR(20)
    , P_INTERMEDIACION DECIMAL(6,3)
    , P_ESPECIAL_EMISION DECIMAL(6,4)
    , P_ESPECIAL_RENOVACION DECIMAL(6,4)
    , FECHA_INICIO_OPESP DATE
    , FECHA_FIN_OPESP DATE
    , DETALLE NVARCHAR(5000)
) 
LANGUAGE SQLSCRIPT 
AS
BEGIN
    RETURN 
        SELECT CT.RAMO
            , CT.IDPRODUCT
            , P.DES_PRODUCT
            , CT.NUM_POLIZA
            , CT.NUM_ANUALIDAD
            , CT.NUM_AVAL_HOST AS CODIGO_AVAL
            , CT.NUM_FIANZA
            , CT.FECHA_INICIO
            , CT.FECHA_FIN
            , CT.NOMBRE_TOMADOR
            , CT.NIF_TOMADOR
            , CT.P_INTERMEDIACION
            , CT.P_ESPECIAL_EMISION
            , CT.P_ESPECIAL_RENOVACION
            , CT.FECHA_INICIO_OPESP
            , CT.FECHA_FIN_OPESP
            , F.DETALLE
        FROM EXT.CARTERA CT
        LEFT JOIN EXT.PRODUCTOS_VW P ON P.IDPRODUCT = CT.IDPRODUCT
        LEFT JOIN (
            SELECT csub.NUM_POLIZA,
                'PRODUCTO|NUM POLIZA|NUM FIANZA|NUM AVAL HOST|FECHA INICIO|FECHA FIN|' ||
                'FECHA EFECTO|FECHA VENCIMIENTO|% INTERMEDIACION|MEDIADOR|ANUALIDAD|' ||
                '% ESPECIAL EMISION|% ESPECIAL RENOVACION|FECHA INICIO OPESP|' ||
                'FECHA FIN OPESP|ACTIVO;' ||
                STRING_AGG(
                    csub.IDPRODUCT || '|' ||
                    csub.IDMODALIDAD || '/' || csub.NUM_POLIZA || '|' ||
                    IFNULL(csub.NUM_FIANZA, '0') || '|' ||
                    IFNULL(csub.NUM_AVAL_HOST, '0') || '|' ||
                    IFNULL(TO_VARCHAR(csub.FECHA_INICIO, 'YYYY-MM-DD'), '') || '|' ||
                    IFNULL(TO_VARCHAR(csub.FECHA_FIN, 'YYYY-MM-DD'), '') || '|' ||
                    IFNULL(TO_VARCHAR(csub.FECHA_EFECTO, 'YYYY-MM-DD'), '') || '|' ||
                    IFNULL(TO_VARCHAR(csub.FECHA_VENCIMIENTO, 'YYYY-MM-DD'), '') || '|' ||
                    IFNULL(csub.P_INTERMEDIACION, '0') || '|' ||
                    csub.COD_MEDIADOR || '-' || csub.COD_SUBCLAVE || '|' ||
                    csub.NUM_ANUALIDAD || '|' ||
                    IFNULL(csub.P_ESPECIAL_EMISION, '0') || '|' ||
                    IFNULL(csub.P_ESPECIAL_RENOVACION, '0') || '|' ||
                    IFNULL(TO_VARCHAR(csub.FECHA_INICIO_OPESP, 'YYYY-MM-DD'), '') || '|' ||
                    IFNULL(TO_VARCHAR(csub.FECHA_FIN_OPESP, 'YYYY-MM-DD'), '') || '|' ||
                    csub.ACTIVO,
                    ';' ORDER BY csub.NUM_ANUALIDAD ASC
                ) DETALLE
            FROM (
                SELECT 
                    c.*, 
                    ROW_NUMBER() OVER (PARTITION BY c.NUM_POLIZA ORDER BY c.NUM_ANUALIDAD ,c.NUM_AVAL_HOST) AS rn
                FROM EXT.CARTERA c 
                WHERE c.ACTIVO <> 0 AND C.COD_MEDIADOR = P_COD_MEDIADOR AND COD_SUBCLAVE = P_COD_SUBCLAVE
                
            ) AS csub 
            WHERE csub.rn > 0
            GROUP BY CSUB.NUM_POLIZA) F ON F.NUM_POLIZA = CT.NUM_POLIZA
        LEFT JOIN (
        		-- FILTRO PARA QUEDARNOS CON LA ANUALIDAD ACTUAL
                SELECT NUM_POLIZA, COD_MEDIADOR, COD_SUBCLAVE, NUM_ANUALIDAD
                    ,ROW_NUMBER() OVER (PARTITION BY CR.NUM_POLIZA, CR.COD_MEDIADOR ORDER BY CR.NUM_ANUALIDAD DESC) AS RN
                FROM EXT.CARTERA CR WHERE CR.RAMO LIKE '%'||UPPER(P_RAMO)||'%' AND CR.ACTIVO > 0
            ) CRT ON CT.NUM_POLIZA = CRT.NUM_POLIZA AND CT.COD_MEDIADOR = CRT.COD_MEDIADOR AND CT.COD_SUBCLAVE = CRT.COD_SUBCLAVE AND CT.NUM_ANUALIDAD = CRT.NUM_ANUALIDAD
        WHERE CT.COD_MEDIADOR = P_COD_MEDIADOR 
            AND CT.COD_SUBCLAVE = P_COD_SUBCLAVE 
            AND CT.RAMO LIKE '%'||UPPER(P_RAMO)||'%' 
            AND (CT.FECHA_FIN >= P_FECHA_TRASPASO OR CT.FECHA_FIN IS NULL) AND (CT.FECHA_INICIO <= P_FECHA_TRASPASO OR CT.FECHA_INICIO IS NULL) 
            --ANUALIDAD ACTUAL
            AND CRT.RN = 1
            AND CT.NUM_POLIZA LIKE '%'||COALESCE(P_NUM_POLIZA,'')||'%'
            AND CT.ACTIVO > 0
        	AND 1 = (CASE
	                    WHEN P_MODIFICAR_RELACION = 0 AND CT.RAMO = 'CREDITO'  THEN 1
	                    WHEN P_MODIFICAR_RELACION = 0 AND (P_RAMO IS NULL OR P_RAMO = '') AND CT.RAMO = 'CAUCION' AND (CT.NUM_AVAL_HOST IS  NULL OR CT.NUM_AVAL_HOST = 0) THEN 1
	                    WHEN P_MODIFICAR_RELACION = 0 AND UPPER(P_RAMO) = 'CAUCION' AND CT.RAMO = 'CAUCION' AND UPPER(P_TIPO_TRASPASO_CAUCION) = 'EXPEDIENTE' AND (CT.NUM_AVAL_HOST IS NULL OR CT.NUM_AVAL_HOST = 0) THEN 1
	                    WHEN P_MODIFICAR_RELACION = 0 AND UPPER(P_RAMO) = 'CAUCION' AND CT.RAMO = 'CAUCION' AND UPPER(P_TIPO_TRASPASO_CAUCION) != 'EXPEDIENTE' AND (CT.NUM_AVAL_HOST IS NOT NULL OR CT.NUM_AVAL_HOST != 0) THEN 1
	                    -- FILTRO MODIFICAR RELACIÓN ACTIVO = 2
	                    WHEN P_MODIFICAR_RELACION = 1 AND CT.RAMO = 'CREDITO'  AND CT.ACTIVO = 2 THEN 1
	                    WHEN P_MODIFICAR_RELACION = 1 AND (P_RAMO IS NULL OR P_RAMO = '') AND CT.RAMO = 'CAUCION' AND (CT.NUM_AVAL_HOST IS  NULL OR CT.NUM_AVAL_HOST = 0) AND CT.ACTIVO = 2 THEN 1
	                    WHEN P_MODIFICAR_RELACION = 1 AND UPPER(P_RAMO) = 'CAUCION' AND CT.RAMO = 'CAUCION' AND UPPER(P_TIPO_TRASPASO_CAUCION) = 'EXPEDIENTE' AND (CT.NUM_AVAL_HOST IS NULL OR CT.NUM_AVAL_HOST = 0) AND CT.ACTIVO = 2 THEN 1
	                    WHEN P_MODIFICAR_RELACION = 1 AND UPPER(P_RAMO) = 'CAUCION' AND CT.RAMO = 'CAUCION' AND UPPER(P_TIPO_TRASPASO_CAUCION) != 'EXPEDIENTE' AND (CT.NUM_AVAL_HOST IS NOT NULL OR CT.NUM_AVAL_HOST != 0) AND CT.ACTIVO = 2 THEN 1
	                    
                	END)
            ORDER BY CT.RAMO DESC,CT.NUM_POLIZA,CT.NUM_ANUALIDAD,CT.NUM_AVAL_HOST
    ; 
    END;

DO BEGIN
SELECT * FROM EXT.GET_BUSCAR_POLIZAS('3013','0000','','EXPEDIENTE','2025-03-07','',0);
-- SELECT * FROM EXT.CARTERA WHERE COD_MEDIADOR = '0004' AND RAMO = 'CREDITO';

-- SELECT *, (select DES_PRODUCT from EXT.PRODUCTOS_VW p where p.IDPRODUCT = car.IDPRODUCT) as DES_PRODUCT, (SELECT 'PRODUCTO|NUM POLIZA|NUM FIANZA|NUM AVAL HOST|FECHA INICIO|FECHA FIN|FECHA EFECTO|FECHA VENCIMIENTO|% INTERMEDIACION|MEDIADOR|ANUALIDAD|% ESPECIAL EMISION|% ESPECIAL RENOVACION|FECHA INICIO OPESP|FECHA FIN OPESP|ACTIVO;' || STRING_AGG( csub.IDPRODUCT || '|' || csub.IDMODALIDAD || '/' || csub.NUM_POLIZA || '|' || IFNULL(csub.NUM_FIANZA,0) || '|' || IFNULL(csub.NUM_AVAL_HOST,0) || '|' || IFNULL(csub.FECHA_INICIO,'') || '|' || IFNULL(csub.FECHA_FIN,'') || '|' || IFNULL(csub.FECHA_EFECTO,'') || '|' || IFNULL(csub.FECHA_VENCIMIENTO,'') || '|' || IFNULL(csub.P_INTERMEDIACION,0) || '|' || csub.COD_MEDIADOR || '-' || csub.COD_SUBCLAVE || '|' || csub.NUM_ANUALIDAD || '|' || IFNULL(csub.P_ESPECIAL_EMISION,0) || '|' || IFNULL(csub.P_ESPECIAL_RENOVACION,0) || '|' || IFNULL(csub.FECHA_INICIO_OPESP,'') || '|' || IFNULL(csub.FECHA_FIN_OPESP,'') || '|' || csub.ACTIVO , ';' ) FROM (SELECT c.*, ROW_NUMBER() OVER (PARTITION BY c.NUM_POLIZA ORDER BY c.NUM_ANUALIDAD) AS rn FROM EXT.CARTERA c WHERE c.NUM_POLIZA = car.NUM_POLIZA AND c.ACTIVO <> 0) AS csub WHERE csub.rn > 0) AS detalle FROM EXT.CARTERA car WHERE COD_MEDIADOR = '0004' AND COD_SUBCLAVE = '0000' AND (FECHA_FIN >= '2025-02-17' OR FECHA_FIN IS NULL) AND (FECHA_INICIO <= '2025-02-17' OR FECHA_INICIO IS NULL) AND FECHA_VENCIMIENTO > '2025-02-17' AND ACTIVO = 1 ORDER BY NUM_POLIZA LIMIT 1000 OFFSET 0;
END;