CREATE OR REPLACE FUNCTION EXT.GET_FECHA_OPERACIONES_ESPECIALES(
	P_COD_MEDIADOR NVARCHAR(10)
	, P_COD_SUBCLAVE NVARCHAR(10)
	, P_RAMO VARCHAR(20)
	, P_NUM_POLIZA NVARCHAR(25)
	, P_DESDE_ANUALIDAD VARCHAR(1) -- C: ACTUAL - N: ANTERIOR
	, P_FECHA_TRASPASO DATE
)
RETURNS TABLE (
     RAMO VARCHAR(20)
    , NUM_POLIZA NVARCHAR(25)
    , COD_MEDIADOR NVARCHAR(10) 
    , COD_SUBCLAVE NVARCHAR(10)
    , NUM_ANUALIDAD INTEGER
    , FECHA_EFECTO DATE
    -- , NUM_AVAL_HOST BIGINT
    -- , NUM_FIANZA DECIMAL(30,0)
     , FECHA_INICIO_OPESP DATE
     , FECHA_FIN_OPESP_ANUALIDAD_ANTERIOR DATE
)  
LANGUAGE SQLSCRIPT 
AS
BEGIN
    RETURN 
    	SELECT DISTINCT C.RAMO, C.NUM_POLIZA, C.COD_MEDIADOR, C.COD_SUBCLAVE, C.NUM_ANUALIDAD
    	, C.FECHA_EFECTO
    	, CASE 
    		WHEN UPPER(P_RAMO) = 'CREDITO' AND UPPER(P_DESDE_ANUALIDAD) = 'C' THEN C.FECHA_EFECTO
    		WHEN UPPER(P_RAMO) = 'CREDITO' AND UPPER(P_DESDE_ANUALIDAD) = 'N' THEN (SELECT FECHA_EFECTO FROM (SELECT CT.FECHA_EFECTO
    												,ROW_NUMBER() OVER (PARTITION BY CT.NUM_POLIZA ORDER BY CT.NUM_ANUALIDAD DESC) AS RN 
    												FROM EXT.CARTERA CT
    												WHERE CT.RAMO = UPPER(P_RAMO)
													    	AND CT.NUM_POLIZA = P_NUM_POLIZA
													    	AND CT.COD_MEDIADOR = P_COD_MEDIADOR AND COD_SUBCLAVE = P_COD_SUBCLAVE
													    	AND CT.ACTIVO = 1
													    	) WHERE RN = 2)
			WHEN UPPER(P_RAMO) = 'CAUCION' THEN P_FECHA_TRASPASO
    	END FECHA_INICIO_OPESP
    --	, NULL FECHA_FIN_OPESP--FECHA_FIN_OPESP
    	, CASE
    		WHEN EXISTS(SELECT 1 FROM (SELECT CT.*
    												,ROW_NUMBER() OVER (PARTITION BY CT.NUM_POLIZA ORDER BY CT.NUM_ANUALIDAD DESC) AS RN 
    												FROM EXT.CARTERA CT
    												WHERE CT.RAMO = UPPER(P_RAMO)
													    	AND CT.NUM_POLIZA = P_NUM_POLIZA
													    	AND CT.COD_MEDIADOR = P_COD_MEDIADOR AND COD_SUBCLAVE = P_COD_SUBCLAVE
													    	AND CT.ACTIVO = 1
													    	) WHERE RN = 2
    															AND (P_ESPECIAL_EMISION IS NOT NULL OR P_ESPECIAL_EMISION <> 0)
    					) THEN (SELECT FECHA_VENCIMIENTO FROM (SELECT CT.FECHA_VENCIMIENTO
    												,ROW_NUMBER() OVER (PARTITION BY CT.NUM_POLIZA ORDER BY CT.NUM_ANUALIDAD DESC) AS RN 
    												FROM EXT.CARTERA CT
    												WHERE CT.RAMO = UPPER(P_RAMO)
													    	AND CT.NUM_POLIZA = P_NUM_POLIZA
													    	AND CT.COD_MEDIADOR = P_COD_MEDIADOR AND COD_SUBCLAVE = P_COD_SUBCLAVE
													    	AND CT.ACTIVO = 1
													    	) WHERE RN = 2
							)
    	END FECHA_FIN_OPESP_ANUALIDAD_ANTERIOR
    	FROM EXT.CARTERA C
    	LEFT JOIN (
        		-- FILTRO PARA QUEDARNOS CON LA ANUALIDAD ACTUAL
                SELECT NUM_POLIZA, COD_MEDIADOR, COD_SUBCLAVE, NUM_ANUALIDAD
                    ,ROW_NUMBER() OVER (PARTITION BY CR.NUM_POLIZA, CR.COD_MEDIADOR ORDER BY CR.NUM_ANUALIDAD DESC) AS RN
                FROM EXT.CARTERA CR WHERE CR.RAMO LIKE '%'||UPPER(P_RAMO)||'%' AND CR.ACTIVO = 1
            ) CRT ON C.NUM_POLIZA = CRT.NUM_POLIZA AND C.COD_MEDIADOR = CRT.COD_MEDIADOR AND C.COD_SUBCLAVE = CRT.COD_SUBCLAVE AND C.NUM_ANUALIDAD = CRT.NUM_ANUALIDAD
    	WHERE RAMO = UPPER(P_RAMO)
    	AND C.ACTIVO = 1
    	AND C.NUM_POLIZA = P_NUM_POLIZA
    	AND C.COD_MEDIADOR = P_COD_MEDIADOR AND C.COD_SUBCLAVE = P_COD_SUBCLAVE
    	AND CRT.RN = 1
    	AND 1 = (CASE
    				WHEN UPPER(P_RAMO) = 'CREDITO' THEN 1
    				WHEN UPPER(P_RAMO) = 'CAUCION' AND C.NUM_FIANZA IS NOT NULL THEN 1
    			END
    	)
    	ORDER BY NUM_POLIZA,NUM_ANUALIDAD
    	;
END;

DO BEGIN
-- UPDATE EXT.CARTERA SET P_ESPECIAL_EMISION = 0.1 WHERE NUM_POLIZA = 9008150 AND NUM_ANUALIDAD = 19;
 SELECT * FROM EXT.GET_FECHA_OPERACIONES_ESPECIALES('0004','0000','CREDITO',9008150,'N','2025-02-20');
--SELECT * FROM EXT.GET_FECHA_OPERACIONES_ESPECIALES('0004','0000','CAUCION',1000257,'C','2025-02-20');
SELECT * FROM EXT.CARTERA WHERE COD_MEDIADOR = '0004' AND RAMO = 'CREDITO' AND NUM_POLIZA = 9008150 ORDER BY NUM_ANUALIDAD;

--SELECT *, (select DES_PRODUCT from EXT.PRODUCTOS_VW p where p.IDPRODUCT = car.IDPRODUCT) as DES_PRODUCT, (SELECT 'PRODUCTO|NUM POLIZA|NUM FIANZA|NUM AVAL HOST|FECHA INICIO|FECHA FIN|FECHA EFECTO|FECHA VENCIMIENTO|% INTERMEDIACION|MEDIADOR|ANUALIDAD|% ESPECIAL EMISION|% ESPECIAL RENOVACION|FECHA INICIO OPESP|FECHA FIN OPESP|ACTIVO;' || STRING_AGG( csub.IDPRODUCT || '|' || csub.IDMODALIDAD || '/' || csub.NUM_POLIZA || '|' || IFNULL(csub.NUM_FIANZA,0) || '|' || IFNULL(csub.NUM_AVAL_HOST,0) || '|' || IFNULL(csub.FECHA_INICIO,'') || '|' || IFNULL(csub.FECHA_FIN,'') || '|' || IFNULL(csub.FECHA_EFECTO,'') || '|' || IFNULL(csub.FECHA_VENCIMIENTO,'') || '|' || IFNULL(csub.P_INTERMEDIACION,0) || '|' || csub.COD_MEDIADOR || '-' || csub.COD_SUBCLAVE || '|' || csub.NUM_ANUALIDAD || '|' || IFNULL(csub.P_ESPECIAL_EMISION,0) || '|' || IFNULL(csub.P_ESPECIAL_RENOVACION,0) || '|' || IFNULL(csub.FECHA_INICIO_OPESP,'') || '|' || IFNULL(csub.FECHA_FIN_OPESP,'') || '|' || csub.ACTIVO , ';' ) FROM (SELECT c.*, ROW_NUMBER() OVER (PARTITION BY c.NUM_POLIZA ORDER BY c.NUM_ANUALIDAD) AS rn FROM EXT.CARTERA c WHERE c.NUM_POLIZA = car.NUM_POLIZA AND c.ACTIVO <> 0) AS csub WHERE csub.rn > 0) AS detalle FROM EXT.CARTERA car WHERE COD_MEDIADOR = '0004' AND COD_SUBCLAVE = '0000' AND (FECHA_FIN >= '2025-02-17' OR FECHA_FIN IS NULL) AND (FECHA_INICIO <= '2025-02-17' OR FECHA_INICIO IS NULL) AND FECHA_VENCIMIENTO > '2025-02-17' AND ACTIVO = 1 ORDER BY NUM_POLIZA LIMIT 1000 OFFSET 0;
END;

SELECT FECHA_EFECTO FROM (SELECT CT.FECHA_EFECTO
    												,ROW_NUMBER() OVER (PARTITION BY cT.NUM_POLIZA ORDER BY cT.NUM_ANUALIDAD DESC) AS RN 
    												FROM EXT.CARTERA CT
    												WHERE CT.RAMO = UPPER('CAUCION')
													    	AND CT.NUM_POLIZA = 22751
													    	AND CT.COD_MEDIADOR = '0004' AND COD_SUBCLAVE = '0000'
													    	) WHERE RN = 2