CREATE OR REPLACE FUNCTION EXT.GET_ANUALIDAD_OP_ESP(
	P_COD_MEDIADOR NVARCHAR(10), P_COD_SUBCLAVE NVARCHAR(10)
	, P_NUM_POLIZA NVARCHAR(25)
)
RETURNS TABLE (
     NUM_ANUALIDAD INTEGER
     , NUM_POLIZA VARCHAR(25)
     , COD_MEDIADOR VARCHAR(10)
     , COD_SUBCLAVE VARCHAR(10)
     , RAMO VARCHAR(10)
     , FECHA_EFECTO DATE
     , FECHA_VENCIMIENTO DATE
     , FECHA_INICIO DATE
     , FECHA_FIN DATE
     , VIGENTE INTEGER
     , VALOR_PL VARCHAR(50)
     
) 
LANGUAGE SQLSCRIPT 
AS
BEGIN
    RETURN 
        SELECT NUM_ANUALIDAD, NUM_POLIZA, COD_MEDIADOR, COD_SUBCLAVE, RAMO, FECHA_EFECTO, FECHA_VENCIMIENTO, FECHA_INICIO, FECHA_FIN
        , CASE
        	WHEN NUM_ANUALIDAD = MAX(NUM_ANUALIDAD) OVER(PARTITION BY NUM_POLIZA, COD_MEDIADOR, COD_SUBCLAVE, RAMO) 
        	THEN 1 ELSE 0
        END VIGENTE
        , NUM_ANUALIDAD || ' | ' || TO_VARCHAR(FECHA_EFECTO, 'DD-MM-YYYY') || ' - ' || TO_VARCHAR(FECHA_VENCIMIENTO, 'DD-MM-YYYY') VALOR_PL
        FROM EXT.CARTERA C
		WHERE C.COD_MEDIADOR = P_COD_MEDIADOR AND C.COD_SUBCLAVE = P_COD_SUBCLAVE
		AND C.RAMO = 'CREDITO' AND C.NUM_POLIZA = P_NUM_POLIZA
		AND C.ACTIVO > 0
		ORDER BY NUM_ANUALIDAD
    ; 
END;

DO BEGIN
	SELECT * FROM EXT.GET_ANUALIDAD_OP_ESP('0004','0000',9008150);
END;