SELECT  T.GENERICATTRIBUTE9,T.GENERICATTRIBUTE10,CAST(R.CREATEDATE AS DATE) FECHA,R.*
FROM (
Select TX.GENERICATTRIBUTE9,
TX.GENERICATTRIBUTE10,
    CR.PERIODSEQ,
    CR.CREDITSEQ,
    MED.POSITIONSEQ,
    MED.POSITIONNAME,
    SO.ORDERID,
    TX.PRODUCTID,
    TX.COMPENSATIONDATE as FECHADATOS,
    (SELECT EXT.LIB_GLOBAL_CESCE:getCompany(TX.GENERICATTRIBUTE11, TX.GENERICATTRIBUTE12).companySapFi FROM DUMMY) AS SOCIEDAD, 
    (SELECT EXT.LIB_GLOBAL_CESCE:getCountry(TX.GENERICATTRIBUTE12).ISOCode FROM DUMMY) AS PAIS,
    TO_NVARCHAR(TO_DATE(TX.COMPENSATIONDATE),  'YYYYMMDD') AS FECHA_CONTABLE,
    TO_NVARCHAR(TO_DATE(TX.COMPENSATIONDATE),  'YYYYMMDD') AS FECHA_DOCUMENTO,
    'SAP COMMISSIONS' AS REFERENCIA, 
    TX.GENERICATTRIBUTE9 AS TIPO_DE_MOVIMIENTO, 
    TX.GENERICATTRIBUTE10 AS SITUACION,
    CASE WHEN (TX.GENERICATTRIBUTE10 = 12 OR TX.GENERICATTRIBUTE10 = 22) THEN 'X' ELSE 'Y' END AS ESTADO,
    CASE WHEN ( CR.VALUE > 0 ) THEN 'P' ELSE 'E' END AS INDICADOR_DE_PRIMA,
    TX.GENERICATTRIBUTE20 AS RIESGO, 
    MED.NATURALEZA AS TIPO_DE_PERSONA,
    MED.CANAL AS TIPO_DE_MEDIADOR,--MED.CANAL_DIST_CIC AS TIPO_DE_MEDIADOR, 
    SUBSTRING(SO.ORDERID, 0, 3) AS MODALIDAD, 
    LPAD(TX.GENERICATTRIBUTE1, 8, '0') AS POLIZA, 
    LPAD(IFNULL(TX.GENERICATTRIBUTE2,0), 6, '0') AS N_RECIBO,
    '' AS N_FACTURA, 
    UT1.NAME AS MONEDA,
    CR.VALUE AS IMPORTE,
    MED.IDHOST AS CODIGO_DE_SUJETO_CESCE, 
    MED.NUM_IDENTIFICACION AS NIF,
    CURRENT_TIMESTAMP AS CREATEDATE,
    'PENDIENTE' as ESTADOREG,
    TX.LINENUMBER AS LINENUMBER,
    TX.SUBLINENUMBER AS SUBLINENUMBER,
    TX.EVENTTYPESEQ  AS EVENTTYPESEQ  
FROM CS_CREDIT CR
INNER JOIN CS_PERIOD PER ON PER.PERIODSEQ = CR.PERIODSEQ AND PER.REMOVEDATE = TO_DATE('22000101','yyyymmdd')
LEFT JOIN CS_SALESTRANSACTION TX ON CR.SALESTRANSACTIONSEQ = TX.SALESTRANSACTIONSEQ
LEFT JOIN CS_SALESORDER SO ON CR.SALESORDERSEQ = SO.SALESORDERSEQ AND SO.REMOVEDATE = TO_DATE('22000101', 'yyyymmdd')
LEFT JOIN CS_UNITTYPE UT1 ON CR.UNITTYPEFORVALUE = UT1.UNITTYPESEQ AND UT1.REMOVEDATE = TO_DATE('22000101', 'yyyymmdd')
LEFT JOIN EXT.MODIFICAR_MEDIADOR MED ON CR.POSITIONSEQ = MED.POSITIONSEQ
LEFT JOIN CS_TRANSACTIONASSIGNMENT TA ON CR.SALESTRANSACTIONSEQ = TA.SALESTRANSACTIONSEQ AND TA.POSITIONNAME = MED.POSITIONNAME
WHERE PER.NAME LIKE 'Julio 2025'
	AND PER.REMOVEDATE = TO_DATE('22000101','yyyymmdd')
	AND ( cr.NAME like 'CD_%_Comision_Emision%' or cr.NAME like 'CD_%_Comision_Renovacion%')

AND TX.GENERICATTRIBUTE9 = 13
--ORDER BY 1,2
) T INNER JOIN EXT.RETORNO_CONTABILIDAD R ON T.PERIODSEQ = R.PERIODSEQ AND T.CREDITSEQ = R.CREDITSEQ AND T.POSITIONSEQ = R.POSITIONSEQ AND R.ORDERID = T.ORDERID
AND T.POLIZA = R.POLIZA AND T.N_RECIBO = R.N_RECIBO
WHERE 1=1
--AND T.PERIODSEQ IS NULL
AND R.TIPO_DE_MOVIMIENTO = 13
ORDER BY 3 desc,1,2

/*
SELECT  * FROM EXT.RETORNO_CONTABILIDAD
WHERE PERIODSEQ = 2533274790397219	-- 2533274790397220
AND CREDITSEQ = 15762598718862733	-- 15762598720325183--15762598720350706	
AND POSITIONSEQ = 4785074604083356	-- 4785074604083447--4785074604083433
AND ORDERID = 51101003913000010	--34109142150000071	--34107517229000003	
*/