-- PÓLIZAS QUE TIENEN ANUALIDADES SIN TRASPASAR 

SELECT T.*,C1.NUM_ANUALIDAD
FROM (
SELECT NUM_POLIZA,COD_MEDIADOR_CEDENTE,SUBCLAVE_CEDENTE,COD_MEDIADOR_RECEPTOR,SUBCLAVE_RECEPTOR,FECHA_EFECTO_SOLICITUD,CASEID--,COUNT(*),
/*CASE WHEN COUNT(*) = (SELECT COUNT(*) 
                      FROM EXT.CARTERA 
                      WHERE COD_MEDIADOR = COD_MEDIADOR_CEDENTE AND COD_SUBCLAVE = SUBCLAVE_CEDENTE 
                      AND FECHA_VENCIMIENTO > FECHA_EFECTO_SOLICITUD AND CAST(CREATEDATE AS DATE) < FECHA_EFECTO_SOLICITUD) THEN 'TOTAL' ELSE 'PARCIAL' END TOTAL_PARCIAL*/
FROM EXT.SOLICITUD_TRASPASO WHERE FECHA_INICIO_TRASPASO = 'I' 
AND RAMO = 'CREDITO'
--AND TIPO_MOVIMIENTO IN (1,2,5)
--AND CASEID IN(2390)
GROUP BY NUM_POLIZA,COD_MEDIADOR_CEDENTE,SUBCLAVE_CEDENTE,COD_MEDIADOR_RECEPTOR,SUBCLAVE_RECEPTOR,FECHA_EFECTO_SOLICITUD,CASEID
ORDER BY CASEID, NUM_POLIZA
) T INNER JOIN EXT.CARTERA C1 ON T.NUM_POLIZA = C1.NUM_POLIZA AND C1.COD_MEDIADOR = T.COD_MEDIADOR_CEDENTE AND C1.COD_SUBCLAVE = T.SUBCLAVE_CEDENTE
LEFT JOIN EXT.CARTERA C2 ON C1.NUM_POLIZA = C2.NUM_POLIZA AND C1.NUM_ANUALIDAD = C2.NUM_ANUALIDAD AND C2.COD_MEDIADOR = T.COD_MEDIADOR_RECEPTOR AND C2.COD_SUBCLAVE = T.SUBCLAVE_RECEPTOR
WHERE C2.NUM_ANUALIDAD IS NULL
ORDER BY CASEID,NUM_ANUALIDAD


-- COMPROBACIÓN
SELECT RAMO,NUM_POLIZA,NUM_ANUALIDAD,COD_MEDIADOR,COD_SUBCLAVE,FECHA_EMISION,FECHA_EFECTO,FECHA_VENCIMIENTO,FECHA_INICIO,FECHA_FIN,ACTIVO,FECHA_EFECTO_TRASPASO FROM EXT.CARTERA
WHERE NUM_POLIZA = 9158972
ORDER BY NUM_POLIZA,NUM_ANUALIDAD